[build]
  publish = "web-frontend/out"
  command = """
  set -e
  rm -rf web-frontend/out
  rm -rf site

  cd web-frontend
  bun ci
  bun run build
  cd ..

  pip install -r docs/requirements.txt
  python -m zensical build --clean --strict

  mkdir -p web-frontend/out/docs
  mv site/* web-frontend/out/docs/
  """

[build.environment]
  NODE_VERSION = "25"
  PYTHON_VERSION = "3.12"
