/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import yaml from 'js-yaml';
import SaveAndLoadPage from '@/app/save-and-load/page';

const mockUseSchedulingData = vi.hoisted(() => vi.fn());
const mockGenerateYamlFromState = vi.hoisted(() => vi.fn());

vi.mock('@/hooks/useSchedulingData', () => ({
  useSchedulingData: mockUseSchedulingData,
}));

vi.mock('@/utils/yamlGenerator', () => ({
  generateYamlFromState: mockGenerateYamlFromState,
}));

describe('SaveAndLoadPage', () => {
  const loadFromYaml = vi.fn();
  const filterAutoGeneratedState = vi.fn((state) => state);
  const fileContentsByName = new Map<string, string>();

  class MockFileReader {
    onload: ((ev: ProgressEvent<FileReader>) => unknown) | null = null;

    readAsText(file: File) {
      const content = fileContentsByName.get(file.name) || '';
      this.onload?.({ target: { result: content } } as unknown as ProgressEvent<FileReader>);
    }
  }

  beforeEach(() => {
    vi.restoreAllMocks();
    loadFromYaml.mockReset();
    filterAutoGeneratedState.mockClear();
    fileContentsByName.clear();

    mockGenerateYamlFromState.mockReturnValue('apiVersion: alpha\ndescription: baseline\n');
    mockUseSchedulingData.mockReturnValue({
      apiVersionData: 'alpha',
      descriptionData: 'baseline',
      dateData: { range: { startDate: undefined, endDate: undefined }, items: [], groups: [] },
      peopleData: { items: [], groups: [], history: [] },
      shiftTypeData: { items: [], groups: [] },
      preferences: [],
      exportData: { formatting: [] },
      loadFromYaml,
      filterAutoGeneratedState,
    });

    vi.stubGlobal('confirm', vi.fn(() => true));
    vi.stubGlobal('alert', vi.fn());
    vi.stubGlobal('FileReader', MockFileReader as unknown as typeof FileReader);
    Object.defineProperty(navigator, 'clipboard', {
      value: {
        writeText: vi.fn().mockResolvedValue(undefined),
      },
      configurable: true,
    });
  });

  it('saves edited YAML and sends parsed object to loadFromYaml', async () => {
    const user = userEvent.setup();

    render(<SaveAndLoadPage />);

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));

    const editor = screen.getByPlaceholderText('Enter YAML configuration...');
    fireEvent.change(editor, { target: { value: 'apiVersion: alpha\ndescription: edited\nappVersion: unknown\n' } });
    await user.click(screen.getByRole('button', { name: /save/i }));

    await waitFor(() => {
      expect(loadFromYaml).toHaveBeenCalledWith(
        expect.objectContaining({ apiVersion: 'alpha', description: 'edited' }),
      );
    });
  });

  it('shows an inline error when YAML parsing fails in edit mode', async () => {
    const user = userEvent.setup();
    vi.spyOn(yaml, 'load').mockImplementationOnce(() => {
      throw new Error('Invalid YAML format');
    });

    render(<SaveAndLoadPage />);

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    fireEvent.change(screen.getByPlaceholderText('Enter YAML configuration...'), {
      target: { value: 'bad: [yaml' },
    });
    await user.click(screen.getByRole('button', { name: /save/i }));

    expect(screen.getByText('Invalid YAML format')).toBeInTheDocument();
    expect(loadFromYaml).not.toHaveBeenCalled();
  });

  it('loads uploaded YAML file and reports success', async () => {
    render(<SaveAndLoadPage />);

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'upload.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('upload.yaml', 'apiVersion: alpha\ndescription: from-upload\nappVersion: unknown\n');

    fireEvent.change(input, { target: { files: [file] } });

    await waitFor(() => {
      expect(loadFromYaml).toHaveBeenCalledWith(
        expect.objectContaining({ description: 'from-upload' }),
      );
    });

    expect(alert).toHaveBeenCalledWith('YAML file loaded successfully!');
  });

  it('does not apply edited YAML when version mismatch confirmation is cancelled', async () => {
    const user = userEvent.setup();
    (confirm as unknown as ReturnType<typeof vi.fn>).mockReturnValue(false);

    render(<SaveAndLoadPage />);

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    fireEvent.change(screen.getByPlaceholderText('Enter YAML configuration...'), {
      target: { value: 'apiVersion: alpha\ndescription: edited\nappVersion: v0.0.1\n' },
    });
    await user.click(screen.getByRole('button', { name: /save/i }));

    expect(confirm).toHaveBeenCalled();
    expect(loadFromYaml).not.toHaveBeenCalled();
  });

  it('does not load uploaded YAML when version mismatch confirmation is cancelled', async () => {
    (confirm as unknown as ReturnType<typeof vi.fn>).mockReturnValue(false);

    render(<SaveAndLoadPage />);

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'upload.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('upload.yaml', 'apiVersion: alpha\ndescription: from-upload\nappVersion: v0.0.1\n');
    fireEvent.change(input, { target: { files: [file] } });

    await waitFor(() => {
      expect(confirm).toHaveBeenCalled();
    });
    expect(loadFromYaml).not.toHaveBeenCalled();
    expect(alert).not.toHaveBeenCalledWith('YAML file loaded successfully!');
  });

  it('logs copy-to-clipboard failure', async () => {
    const user = userEvent.setup();
    const writeText = vi.fn().mockRejectedValue(new Error('clipboard denied'));
    Object.defineProperty(navigator, 'clipboard', {
      value: { writeText },
      configurable: true,
    });
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    render(<SaveAndLoadPage />);

    await user.click(screen.getByRole('button', { name: /copy/i }));

    await waitFor(() => {
      expect(writeText).toHaveBeenCalled();
      expect(errorSpy).toHaveBeenCalledWith('Failed to copy to clipboard:', expect.any(Error));
    });
  });

  it('triggers blob URL download and revokes it', async () => {
    const user = userEvent.setup();
    const createSpy = vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:mock-url');
    const revokeSpy = vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);

    render(<SaveAndLoadPage />);

    await user.click(screen.getByRole('button', { name: /download/i }));

    expect(createSpy).toHaveBeenCalled();
    expect(revokeSpy).toHaveBeenCalledWith('blob:mock-url');
  });

  it('alerts when uploaded YAML file has no content', () => {
    render(<SaveAndLoadPage />);

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'empty.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('empty.yaml', '');

    fireEvent.change(input, { target: { files: [file] } });

    expect(alert).toHaveBeenCalledWith('No content found in the uploaded file.');
    expect(loadFromYaml).not.toHaveBeenCalled();
  });

  it('alerts on invalid uploaded YAML parsing errors', () => {
    const yamlSpy = vi.spyOn(yaml, 'load').mockImplementationOnce(() => {
      throw new Error('bad yaml');
    });

    render(<SaveAndLoadPage />);

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'broken.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('broken.yaml', 'bad: [yaml');

    fireEvent.change(input, { target: { files: [file] } });

    expect(yamlSpy).toHaveBeenCalled();
    expect(alert).toHaveBeenCalledWith('Error loading YAML file: bad yaml');
    expect(loadFromYaml).not.toHaveBeenCalled();
  });

  it('loads partial YAML payloads after version warning confirmation', () => {
    render(<SaveAndLoadPage />);

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'partial.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('partial.yaml', 'description: partial\n');

    fireEvent.change(input, { target: { files: [file] } });

    expect(confirm).toHaveBeenCalled();
    expect(loadFromYaml).toHaveBeenCalledWith(expect.objectContaining({ description: 'partial' }));
    expect(alert).toHaveBeenCalledWith('YAML file loaded successfully!');
  });

  it('passes through unknown top-level keys when loading uploaded YAML', () => {
    render(<SaveAndLoadPage />);

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'unknown-keys.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('unknown-keys.yaml', 'description: partial\ncustomFlag: true\n');

    fireEvent.change(input, { target: { files: [file] } });

    expect(loadFromYaml).toHaveBeenCalledWith(
      expect.objectContaining({ description: 'partial', customFlag: true }),
    );
  });

  it('saves sparse edited YAML objects without surfacing an inline parse error', async () => {
    const user = userEvent.setup();

    render(<SaveAndLoadPage />);

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    fireEvent.change(screen.getByPlaceholderText('Enter YAML configuration...'), {
      target: { value: 'people:\n  items:\n    - id: P1\n' },
    });
    await user.click(screen.getByRole('button', { name: /save/i }));

    await waitFor(() => {
      expect(loadFromYaml).toHaveBeenCalledWith(
        expect.objectContaining({
          people: expect.objectContaining({
            items: [expect.objectContaining({ id: 'P1' })],
          }),
        }),
      );
    });
    expect(screen.queryByText(/invalid yaml format/i)).not.toBeInTheDocument();
  });
});
