/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// React hook for scheduling data management with localStorage
'use client';

import { useState, useEffect } from 'react';
import { Item, Group, DateRange, ShiftTypeRequirementsPreference, ShiftRequestPreference, ShiftTypeSuccessionsPreference, ShiftCountPreference, ShiftAffinityPreference, DataType, Preference, AT_MOST_ONE_SHIFT_PER_DAY, SHIFT_TYPE_REQUIREMENT, SHIFT_REQUEST, SHIFT_TYPE_SUCCESSIONS, SHIFT_COUNT, SHIFT_AFFINITY, ExportConfig, ExportFormatting, ExportExtraColumn, ExportExtraRow } from '@/types/scheduling';
import { ItemGroupEditorPageData } from '@/components/ItemGroupEditorPage';
import { AUTO_GENERATED_ITEMS, AUTO_GENERATED_GROUPS, isReservedKeyword, filterAutoGenerated, API_VERSION, ALL, OFF, WEEKDAY, WEEKEND, SATURDAY, SUNDAY } from '@/utils/keywords';
import { setLatestSchedulingStateForSentry } from '@/utils/sentrySchedulingState';
import { buildTaiwanHolidayGroups, isTaiwanHolidayRangeSupported } from '@/utils/taiwanHolidays';
import { ERROR_SHOULD_NOT_HAPPEN } from '@/constants/errors';
import {
  compareFirstIdByEntryOrder,
  getOrderedEntries,
  sortIdsByEntryOrder,
  sortPairsByFirstIdEntryOrder,
} from '@/utils/entityOrdering';

export interface SchedulingState {
  apiVersion: string | number;
  description: string;
  dates: { range: DateRange, items: Item[]; groups: Group[] };
  people: { items: Item[]; groups: Group[] };
  shiftTypes: { items: Item[]; groups: Group[] };
  preferences: Preference[];
  export?: ExportConfig;
}

interface HistoryState {
  state: SchedulingState;
  history: SchedulingState[];
  currentHistoryIndex: number;
}

const STORAGE_KEY = 'nurse-scheduling-data';
const WORKER_NAMESPACE_KEY = '__PLAYWRIGHT_WORKER_NAMESPACE__';
const MAX_HISTORY_SIZE = 50;

// Constants for infinity value handling in localStorage
// JSON.stringify converts Infinity to null and JSON.parse doesn't handle infinity properly
// These placeholders allow us to safely store and retrieve infinity values
const INFINITY_PLACEHOLDER = '__INFINITY__';
const NEGATIVE_INFINITY_PLACEHOLDER = '__NEGATIVE_INFINITY__';
const WORKDAY = 'WORKDAY';
const FREEDAY = 'FREEDAY';
const DEFAULT_SEPARATOR_COLOR = '#000000';

interface UpdateDateRangeOptions {
  importTaiwanHolidays?: boolean;
}

interface HistoryMutationOptions {
  replaceLatestHistoryEntry?: boolean;
}

type NullableShiftTypeRequirementsPreference = Omit<ShiftTypeRequirementsPreference, 'qualifiedPeople'> & {
  qualifiedPeople?: ShiftTypeRequirementsPreference['qualifiedPeople'] | null;
};

function normalizeQualifiedPeopleForFrontend(
  qualifiedPeople: NullableShiftTypeRequirementsPreference['qualifiedPeople']
): string[] {
  return qualifiedPeople === null || qualifiedPeople === undefined ? [ALL] : qualifiedPeople;
}

function normalizePreferenceOrder(pref: Preference, state: SchedulingState): Preference {
  const peopleEntries = getOrderedEntries(state.people);
  const shiftTypeEntries = getOrderedEntries(state.shiftTypes);
  const dateEntries = getOrderedEntries(state.dates);

  if (pref.type === SHIFT_TYPE_REQUIREMENT) {
    const requirementPref = pref as NullableShiftTypeRequirementsPreference;
    return {
      ...requirementPref,
      shiftType: sortIdsByEntryOrder(requirementPref.shiftType, shiftTypeEntries),
      qualifiedPeople: sortIdsByEntryOrder(normalizeQualifiedPeopleForFrontend(requirementPref.qualifiedPeople), peopleEntries),
      date: sortIdsByEntryOrder(requirementPref.date, dateEntries),
    };
  }
  if (pref.type === SHIFT_REQUEST) {
    return {
      ...pref,
      person: sortIdsByEntryOrder(pref.person, peopleEntries),
      date: sortIdsByEntryOrder(pref.date, dateEntries),
      shiftType: sortIdsByEntryOrder(pref.shiftType, shiftTypeEntries),
    };
  }
  if (pref.type === SHIFT_TYPE_SUCCESSIONS) {
    return {
      ...pref,
      person: sortIdsByEntryOrder(pref.person, peopleEntries),
      date: sortIdsByEntryOrder(pref.date, dateEntries),
    };
  }
  if (pref.type === SHIFT_COUNT) {
    return {
      ...pref,
      person: sortIdsByEntryOrder(pref.person, peopleEntries),
      countDates: sortIdsByEntryOrder(pref.countDates, dateEntries),
      countShiftTypes: sortIdsByEntryOrder(pref.countShiftTypes, shiftTypeEntries),
      countShiftTypeCoefficients: sortPairsByFirstIdEntryOrder(pref.countShiftTypeCoefficients, shiftTypeEntries),
    };
  }
  if (pref.type === SHIFT_AFFINITY) {
    return {
      ...pref,
      date: sortIdsByEntryOrder(pref.date, dateEntries),
      people1: sortIdsByEntryOrder(pref.people1, peopleEntries),
      people2: sortIdsByEntryOrder(pref.people2, peopleEntries),
      shiftTypes: sortIdsByEntryOrder(pref.shiftTypes, shiftTypeEntries),
    };
  }
  return pref;
}

function sortPreferencesByType(preferences: Preference[]): Preference[] {
  const typeOrder = [AT_MOST_ONE_SHIFT_PER_DAY, SHIFT_TYPE_REQUIREMENT, SHIFT_REQUEST, SHIFT_TYPE_SUCCESSIONS, SHIFT_COUNT, SHIFT_AFFINITY];
  return [...preferences].sort((a, b) => typeOrder.indexOf(a.type) - typeOrder.indexOf(b.type));
}

function sortShiftRequestsByEntityOrder(preferences: ShiftRequestPreference[], state: SchedulingState): ShiftRequestPreference[] {
  const peopleEntries = getOrderedEntries(state.people);
  const shiftTypeEntries = getOrderedEntries(state.shiftTypes);
  // Sort requests by person, then shift type, then weight; request dates are
  // normalized inside each request rather than used for list-level ordering.
  return [...preferences].sort((a, b) => {
    const personOrder = compareFirstIdByEntryOrder(a.person, b.person, peopleEntries);
    if (personOrder !== 0) return personOrder;
    const shiftTypeOrder = compareFirstIdByEntryOrder(a.shiftType, b.shiftType, shiftTypeEntries);
    if (shiftTypeOrder !== 0) return shiftTypeOrder;
    return a.weight - b.weight;
  });
}

// Normalize IDs within each preference, order shift requests by entities, then
// group all preferences by type for stable saved/exported state.
function normalizePreferencesOrder(preferences: Preference[], state: SchedulingState): Preference[] {
  const normalizedPreferences = preferences.map(pref => normalizePreferenceOrder(pref, state));
  const sortedShiftRequests = sortShiftRequestsByEntityOrder(
    normalizedPreferences.filter((pref): pref is ShiftRequestPreference => pref.type === SHIFT_REQUEST),
    state
  );
  const otherPreferences = normalizedPreferences.filter(pref => pref.type !== SHIFT_REQUEST);

  return sortPreferencesByType([
    ...otherPreferences,
    ...sortedShiftRequests,
  ]);
}

function normalizeExportFormattingOrder(formatting: ExportFormatting[] | undefined, state: SchedulingState) {
  if (!formatting) return formatting;

  const peopleEntries = getOrderedEntries(state.people);
  const shiftTypeEntries = getOrderedEntries(state.shiftTypes);
  const dateEntries = getOrderedEntries(state.dates);

  return formatting.map(rule => {
    let updatedRule = { ...rule };
    if ('people' in updatedRule) {
      updatedRule = { ...updatedRule, people: sortIdsByEntryOrder(updatedRule.people, peopleEntries) };
    }
    if ('dates' in updatedRule) {
      updatedRule = { ...updatedRule, dates: sortIdsByEntryOrder(updatedRule.dates, dateEntries) };
    }
    if ('shiftTypes' in updatedRule) {
      updatedRule = { ...updatedRule, shiftTypes: sortIdsByEntryOrder(updatedRule.shiftTypes, shiftTypeEntries) };
    }
    return updatedRule;
  });
}

function normalizeExportExtraColumnsOrder(extraColumns: ExportExtraColumn[] | undefined, state: SchedulingState) {
  if (!extraColumns) return extraColumns;

  const shiftTypeEntries = getOrderedEntries(state.shiftTypes);
  const dateEntries = getOrderedEntries(state.dates);
  return extraColumns.map(rule => ({
    ...rule,
    countShiftTypes: sortIdsByEntryOrder(rule.countShiftTypes, shiftTypeEntries),
    countDates: sortIdsByEntryOrder(rule.countDates, dateEntries),
  }));
}

function normalizeExportExtraRowsOrder(extraRows: ExportExtraRow[] | undefined, state: SchedulingState) {
  if (!extraRows) return extraRows;

  const peopleEntries = getOrderedEntries(state.people);
  const shiftTypeEntries = getOrderedEntries(state.shiftTypes);
  return extraRows.map(rule => ({
    ...rule,
    countShiftTypes: sortIdsByEntryOrder(rule.countShiftTypes, shiftTypeEntries),
    countPeople: sortIdsByEntryOrder(rule.countPeople, peopleEntries),
  }));
}

function normalizeExportConfigOrder(exportConfig: ExportConfig | undefined, state: SchedulingState) {
  if (!exportConfig) return exportConfig;

  return {
    ...exportConfig,
    formatting: normalizeExportFormattingOrder(exportConfig.formatting, state),
    extraColumns: normalizeExportExtraColumnsOrder(exportConfig.extraColumns, state),
    extraRows: normalizeExportExtraRowsOrder(exportConfig.extraRows, state),
  };
}

// Helper function to generate date items from a date range
function _generateDateItems(startDate: Date, endDate: Date): Item[] {
  const dates: Item[] = [];

  // Determine ID format based on date range scope
  const sameYear = startDate.getUTCFullYear() === endDate.getUTCFullYear();
  const sameMonth = sameYear && startDate.getUTCMonth() === endDate.getUTCMonth();

  for (let date = new Date(startDate); date <= endDate; date.setUTCDate(date.getUTCDate() + 1)) {
    const dateStr = date.toISOString().split('T')[0];
    const dayName = date.toLocaleDateString('en-US', { weekday: 'long', timeZone: 'UTC' });
    const formattedDate = date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      timeZone: 'UTC'
    });

    // Generate ID based on date range scope
    let id: string;
    if (sameMonth) {
      id = dateStr.slice(-2); // DD
    } else if (sameYear) {
      id = dateStr.slice(5); // MM-DD
    } else {
      id = dateStr; // YYYY-MM-DD
    }

    dates.push({
      id,
      description: `${dayName}, ${formattedDate}`
    });
  }

  return dates;
}

function _generateAutoGeneratedItems(dataType: DataType, dateRange?: DateRange): Item[] {
  const autoGeneratedItems: Item[] = [];

  if (dataType === DataType.DATES && dateRange?.startDate && dateRange?.endDate) {
    autoGeneratedItems.push(
      ..._generateDateItems(dateRange.startDate, dateRange.endDate).map(date => ({
        id: date.id,
        description: date.description,
        isAutoGenerated: true
      }))
    );
  }
  autoGeneratedItems.push(
    ...AUTO_GENERATED_ITEMS[dataType].map(autoItem => ({
      id: autoItem.id,
      description: autoItem.description,
      isAutoGenerated: true
    }))
  );

  return autoGeneratedItems;
}

function _generateAutoGeneratedGroups(dataType: DataType, items: Item[], dateRange?: DateRange): Group[] {
  let filteredItems = filterAutoGenerated(items);
  if (dataType === DataType.DATES && dateRange?.startDate && dateRange?.endDate) {
    filteredItems = _generateDateItems(dateRange.startDate, dateRange.endDate);
  }
  return AUTO_GENERATED_GROUPS[dataType].map(autoGroup => ({
    id: autoGroup.id,
    members: autoGroup.generateMembers(filteredItems, dateRange),
    description: autoGroup.description,
    isAutoGenerated: true
  }));
}

function filterAutoGeneratedState(state: SchedulingState): SchedulingState {
  return {
    ...state,
    dates: {
      ...state.dates,
      items: filterAutoGenerated(state.dates.items) as Item[],
      groups: filterAutoGenerated(state.dates.groups) as Group[]
    },
    people: {
      items: filterAutoGenerated(state.people.items) as Item[],
      groups: filterAutoGenerated(state.people.groups) as Group[]
    },
    shiftTypes: {
      ...state.shiftTypes,
      items: filterAutoGenerated(state.shiftTypes.items) as Item[],
      groups: filterAutoGenerated(state.shiftTypes.groups) as Group[]
    }
  };
}

function addAutoGeneratedToState(state: SchedulingState): SchedulingState {
  const filteredState = filterAutoGeneratedState(state);
  return {
    ...state,
    dates: {
      ...state.dates,
      items: [...filteredState.dates.items, ..._generateAutoGeneratedItems(DataType.DATES, state.dates.range)],
      groups: [...filteredState.dates.groups, ..._generateAutoGeneratedGroups(DataType.DATES, state.dates.items, state.dates.range)]
    },
    people: {
      items: [...filteredState.people.items, ..._generateAutoGeneratedItems(DataType.PEOPLE)],
      groups: [...filteredState.people.groups, ..._generateAutoGeneratedGroups(DataType.PEOPLE, state.people.items)]
    },
    shiftTypes: {
      ...state.shiftTypes,
      items: [...filteredState.shiftTypes.items, ..._generateAutoGeneratedItems(DataType.SHIFT_TYPES)],
      groups: [...filteredState.shiftTypes.groups, ..._generateAutoGeneratedGroups(DataType.SHIFT_TYPES, state.shiftTypes.items)]
    }
  };
}

function normalizeStateForFrontend(state: SchedulingState): SchedulingState {
  const stateWithAutoGenerated = addAutoGeneratedToState(state);
  return {
    ...stateWithAutoGenerated,
    preferences: normalizePreferencesOrder(stateWithAutoGenerated.preferences, stateWithAutoGenerated),
    export: normalizeExportConfigOrder(stateWithAutoGenerated.export, stateWithAutoGenerated),
  };
}

function replaceDateGroups(existingGroups: Group[], replacementGroups: Group[]): Group[] {
  if (replacementGroups.length === 0) {
    return existingGroups;
  }

  const replacementIds = new Set(replacementGroups.map(group => group.id.toLowerCase()));
  return [
    ...existingGroups.filter(group => !replacementIds.has(group.id.toLowerCase())),
    ...replacementGroups,
  ];
}

// Helper function to convert infinity/-infinity values to safe string representations
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function replaceInfinityValues(obj: any): any {
  if (obj === null || typeof obj !== 'object') {
    if (obj === Infinity) return INFINITY_PLACEHOLDER;
    if (obj === -Infinity) return NEGATIVE_INFINITY_PLACEHOLDER;
    return obj;
  }

  if (Array.isArray(obj)) {
    return obj.map(replaceInfinityValues);
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const result: any = {};
  for (const key in obj) {
    if (obj.hasOwnProperty(key)) {
      result[key] = replaceInfinityValues(obj[key]);
    }
  }
  return result;
}

// Helper function to restore infinity/-infinity values from safe string representations
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function restoreInfinityValues(obj: any): any {
  if (obj === null || typeof obj !== 'object') {
    if (obj === INFINITY_PLACEHOLDER) return Infinity;
    if (obj === NEGATIVE_INFINITY_PLACEHOLDER) return -Infinity;
    return obj;
  }

  if (Array.isArray(obj)) {
    return obj.map(restoreInfinityValues);
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const result: any = {};
  for (const key in obj) {
    if (obj.hasOwnProperty(key)) {
      result[key] = restoreInfinityValues(obj[key]);
    }
  }
  return result;
}

function createDefaultPeople() {
  return {
    items: Array.from({ length: 10 }, (_, index) => ({
      id: `Person ${index + 1}`,
      description: '',
      history: [] // Start with empty history
    })),
    groups: [
      { id: 'Group 1', members: ['Person 1', 'Person 2'], description: '' },
      { id: 'Group 2', members: ['Person 2', 'Person 3', 'Person 4'], description: '' },
      { id: 'Group 3', members: ['Person 3', 'Person 4', 'Person 5', 'Person 6'], description: '' },
      { id: 'Group 4', members: ['Person 4', 'Person 5', 'Person 6', 'Person 7', 'Person 8'], description: '' },
      { id: 'Group 5', members: ['Person 5', 'Person 6', 'Person 7', 'Person 8', 'Person 9', 'Person 10'], description: '' },
    ]
  };
}

function createDefaultShiftTypes() {
  return {
    items: [
      { id: 'D', description: 'Day (All Levels)' },
      { id: 'D+', description: 'Day (Senior Only)' },
      { id: 'E', description: 'Evening (All Levels)' },
      { id: 'E+', description: 'Evening (Senior Only)' },
      { id: 'N', description: 'Night (All Levels)' },
      { id: 'N+', description: 'Night (Senior Only)' },
      { id: 'A', description: 'Admin (All Levels)' },
      { id: 'A+', description: 'Admin (Senior Only)' },
      { id: 'A-', description: 'Admin (Assistant Only)' },
    ],
    groups: [
      { id: 'Day', members: ['D', 'D+'], description: 'All day shift types' },
      { id: 'Evening', members: ['E', 'E+'], description: 'All evening shift types' },
      { id: 'Night', members: ['N', 'N+'], description: 'All night shift types' },
      { id: 'Administrative', members: ['A', 'A+', 'A-'], description: 'All administrative shift types' },
    ]
  };
}

function generateShiftTypeCountExtraColumns(shiftTypes: { items: Item[]; groups: Group[] }): ExportExtraColumn[] {
  const shiftTypeItems = filterAutoGenerated(shiftTypes.items) as Item[];
  const shiftTypeGroups = filterAutoGenerated(shiftTypes.groups) as Group[];

  return [
    ...shiftTypeItems.map((shiftType, index) => ({
      description: '',
      type: 'count' as const,
      header: `${shiftType.id} Count`,
      countShiftTypes: [shiftType.id],
      countDates: [ALL],
      ...(index === shiftTypeItems.length - 1 ? { rightBorderColor: DEFAULT_SEPARATOR_COLOR } : {})
    })),
    ...shiftTypeGroups.map(group => ({
      description: '',
      type: 'count' as const,
      header: `${group.id} Count`,
      countShiftTypes: [group.id],
      countDates: [ALL]
    }))
  ];
}

function generateShiftTypeCountExtraRows(shiftTypes: { items: Item[]; groups: Group[] }): ExportExtraRow[] {
  const shiftTypeItems = filterAutoGenerated(shiftTypes.items) as Item[];
  const shiftTypeGroups = filterAutoGenerated(shiftTypes.groups) as Group[];

  return [
    ...shiftTypeItems.map((shiftType, index) => ({
      description: '',
      type: 'count' as const,
      header: `${shiftType.id} Count`,
      countShiftTypes: [shiftType.id],
      countPeople: [ALL],
      ...(index === shiftTypeItems.length - 1 ? { bottomBorderColor: DEFAULT_SEPARATOR_COLOR } : {})
    })),
    ...shiftTypeGroups.map(group => ({
      description: '',
      type: 'count' as const,
      header: `${group.id} Count`,
      countShiftTypes: [group.id],
      countPeople: [ALL]
    }))
  ];
}

export function generateExportLayoutConfig(
  shiftTypes: { items: Item[]; groups: Group[] },
  dateGroups: Group[] = []
): ExportConfig {
  const hasWorkdayGroup = dateGroups.some(group => group.id === WORKDAY);
  const hasFreedayGroup = dateGroups.some(group => group.id === FREEDAY);
  const workdayFreedayColumns: ExportExtraColumn[] = [
    ...(hasWorkdayGroup ? [{
      description: '',
      type: 'count' as const,
      header: `OFF (${WORKDAY})`,
      countShiftTypes: [OFF],
      countDates: [WORKDAY]
    }] : []),
    ...(hasFreedayGroup ? [{
      description: '',
      type: 'count' as const,
      header: `OFF (${FREEDAY})`,
      countShiftTypes: [OFF],
      countDates: [FREEDAY]
    }] : [])
  ];
  if (workdayFreedayColumns.length > 0) {
    workdayFreedayColumns[workdayFreedayColumns.length - 1].rightBorderColor = DEFAULT_SEPARATOR_COLOR;
  }

  return {
    formatting: [
      {
        description: 'Show requested shift request target',
        type: 'cell',
        appendText: ' [{shiftType}]',
        people: [ALL],
        dates: [ALL],
        shiftTypes: [ALL, OFF],
        when: {
          preference: {
            types: ['shift request'],
            requestShape: ['person-item-to-date-item'],
            weightRange: [-Infinity, Infinity]
          }
        }
      },
      {
        description: 'Mark unsatisfied shift requests',
        type: 'cell',
        appendText: ' [X]',
        fontColor: '#c00000',
        note: {
          text: 'Weight of unmet single-style request: {totalAbsWeight}'
        },
        people: [ALL],
        dates: [ALL],
        shiftTypes: [ALL, OFF],
        when: {
          preference: {
            types: ['shift request'],
            requestShape: ['person-item-to-date-item'],
            satisfied: false,
            weightRange: [-Infinity, Infinity]
          }
        }
      },
      {
        description: '',
        type: 'history header',
        backgroundColor: '#fefce8'
      },
      {
        description: '',
        type: 'history',
        people: [ALL],
        backgroundColor: '#fefce8'
      },
      {
        description: '',
        type: 'column',
        dates: [SATURDAY, SUNDAY],
        backgroundColor: '#dbeafe'
      },
      {
        description: '',
        type: 'column',
        dates: [SATURDAY],
        rightBorderColor: '#9ca3af'
      },
      ...(hasFreedayGroup ? [{
        description: '',
        type: 'column' as const,
        dates: [FREEDAY],
        backgroundColor: '#dcfce7'
      }] : [])
    ],
    extraColumns: [
      {
        description: '',
        type: 'count',
        header: 'OFF (Total)',
        countShiftTypes: [OFF],
        countDates: [ALL],
        rightBorderColor: DEFAULT_SEPARATOR_COLOR
      },
      ...workdayFreedayColumns,
      {
        description: '',
        type: 'count',
        header: 'OFF (Weekday)',
        countShiftTypes: [OFF],
        countDates: [WEEKDAY]
      },
      {
        description: '',
        type: 'count',
        header: 'OFF (Weekend)',
        countShiftTypes: [OFF],
        countDates: [WEEKEND],
        rightBorderColor: DEFAULT_SEPARATOR_COLOR
      },
      ...generateShiftTypeCountExtraColumns(shiftTypes)
    ],
    extraRows: [
      ...generateShiftTypeCountExtraRows(shiftTypes)
    ]
  };
}

function createDefaultState(): SchedulingState {
  const shiftTypes = createDefaultShiftTypes();
  const dates = {
    range: { startDate: undefined, endDate: undefined },
    items: [],
    groups: [
      {
        id: WORKDAY,
        members: [],
        description: 'Workdays'
      },
      {
        id: FREEDAY,
        members: [],
        description: 'Freedays'
      }
    ]
  };
  return {
    apiVersion: API_VERSION,
    description: '',
    dates,
    people: createDefaultPeople(),
    shiftTypes,
    preferences: [
      {
        type: AT_MOST_ONE_SHIFT_PER_DAY
      }
    ]
  };
}

function createDefaultHistoryState(): HistoryState {
  const defaultState = addAutoGeneratedToState(createDefaultState());
  return {
    state: defaultState,
    history: [defaultState],
    currentHistoryIndex: 0
  };
}

function loadStateFromStorage(): HistoryState {
  if (typeof window === 'undefined') return createDefaultHistoryState();

  try {
    const stored = localStorage.getItem(getStorageKey());

    if (!stored) return createDefaultHistoryState();

    const parsedHistoryState = restoreInfinityValues(JSON.parse(stored)) as HistoryState;

    for (const state of [...parsedHistoryState.history, parsedHistoryState.state]) {
      state.dates.range.startDate = state.dates.range.startDate ? new Date(state.dates.range.startDate) : undefined;
      state.dates.range.endDate = state.dates.range.endDate ? new Date(state.dates.range.endDate) : undefined;
    }

    const currentState = normalizeStateForFrontend(parsedHistoryState.state);

    return {
      state: currentState,
      history: parsedHistoryState.history.map(normalizeStateForFrontend),
      currentHistoryIndex: Math.min(parsedHistoryState.currentHistoryIndex || 0, parsedHistoryState.history.length - 1)
    };
  } catch (error) {
    console.error('Failed to load data from localStorage:', error);
    return createDefaultHistoryState();
  }
}

function saveStateToStorage(historyState: HistoryState): void {
  if (typeof window === 'undefined') return;

  try {
    // Store the complete history state, but exclude auto-generated groups and computed date items
    const historyStateToStore = {
      state: {
        ...filterAutoGeneratedState(historyState.state),
        dates: {
          ...filterAutoGeneratedState(historyState.state).dates,
          range: {
            startDate: historyState.state.dates.range.startDate?.toISOString().split('T')[0],
            endDate: historyState.state.dates.range.endDate?.toISOString().split('T')[0]
          },
          items: undefined  // Don't store computed items
        }
      },
      history: historyState.history.map(state => ({
        ...filterAutoGeneratedState(state),
        dates: {
          ...filterAutoGeneratedState(state).dates,
          range: {
            startDate: state.dates.range.startDate?.toISOString().split('T')[0],
            endDate: state.dates.range.endDate?.toISOString().split('T')[0]
          },
          items: undefined  // Don't store computed items
        }
      })),
      currentHistoryIndex: historyState.currentHistoryIndex
    };

    // Replace infinity values with safe placeholders before JSON.stringify
    const safeHistoryState = replaceInfinityValues(historyStateToStore);
    localStorage.setItem(getStorageKey(), JSON.stringify(safeHistoryState));
  } catch (error) {
    console.error('Failed to save data to localStorage:', error);
  }
}

function getStorageKey(): string {
  if (typeof window === 'undefined') return STORAGE_KEY;

  const workerNamespace = (window as unknown as { [WORKER_NAMESPACE_KEY]?: string })[WORKER_NAMESPACE_KEY];
  return workerNamespace ? `${STORAGE_KEY}__${workerNamespace}` : STORAGE_KEY;
}

function addToHistory(
  currentHistoryState: HistoryState,
  newState: SchedulingState,
  options: HistoryMutationOptions = {}
): HistoryState {
  // Remove any future history if we're not at the end
  const trimmedHistory = currentHistoryState.history.slice(0, currentHistoryState.currentHistoryIndex + 1);

  const newHistory =
    options.replaceLatestHistoryEntry && trimmedHistory.length > 0
      ? [...trimmedHistory.slice(0, -1), newState]
      : [...trimmedHistory, newState];

  // Limit history size
  const limitedHistory = newHistory.length > MAX_HISTORY_SIZE
    ? newHistory.slice(-MAX_HISTORY_SIZE)
    : newHistory;

  const newIndex = limitedHistory.length - 1;

  return {
    state: newState,
    history: limitedHistory,
    currentHistoryIndex: newIndex
  };
}

// Main hook for external use
export function useSchedulingData() {
  const [historyState, setHistoryState] = useState<HistoryState>(createDefaultHistoryState);

  useEffect(() => {
    setLatestSchedulingStateForSentry(historyState.state, filterAutoGeneratedState);
  }, [historyState.state]);

  // Load from localStorage on mount
  useEffect(() => {
    const storedHistoryState = loadStateFromStorage();
    setHistoryState(storedHistoryState);
  }, []);

  // Global keyboard shortcuts for undo/redo
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      // Check if Ctrl (or Cmd on Mac) is pressed
      const isCtrlOrCmd = event.ctrlKey || event.metaKey;

      if (!isCtrlOrCmd || event.altKey || event.shiftKey) return;

      // Undo: Ctrl+Z
      if (event.key === 'z') {
        event.preventDefault();
        undo();
        return;
      }

      // Redo: Ctrl+Y
      if (event.key === 'y') {
        event.preventDefault();
        redo();
        return;
      }
    };

    // Add event listener to document
    document.addEventListener('keydown', handleKeyDown);

    // Cleanup function to remove event listener
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  });

  // Generic update function that handles both state update and storage
  const updateState = (
    updater: (prevState: SchedulingState) => SchedulingState,
    options: HistoryMutationOptions = {}
  ) => {
    setHistoryState(prevHistoryState => {
      const newState = addAutoGeneratedToState(updater(prevHistoryState.state));
      const newHistoryState = addToHistory(prevHistoryState, newState, options);
      saveStateToStorage(newHistoryState);
      return newHistoryState;
    });
  };

  // Base function to navigate to a specific history index
  const moveHistoryIndex = (delta: number) => {
    setHistoryState(prevHistoryState => {
      const targetIndex = prevHistoryState.currentHistoryIndex + delta;

      // Validate target index bounds
      if (targetIndex < 0 || targetIndex >= prevHistoryState.history.length || targetIndex === prevHistoryState.currentHistoryIndex) {
        return prevHistoryState;
      }

      const targetState = prevHistoryState.history[targetIndex];

      const restoredState = addAutoGeneratedToState(targetState);

      const newHistoryState = {
        ...prevHistoryState,
        state: restoredState,
        currentHistoryIndex: targetIndex
      };

      saveStateToStorage(newHistoryState);
      return newHistoryState;
    });
  };

  // Undo function
  const undo = () => {
    moveHistoryIndex(-1);
  };

  // Redo function
  const redo = () => {
    moveHistoryIndex(1);
  };

  const updateDateRange = (dateRange: DateRange, options: UpdateDateRangeOptions = {}) => {
    // First, determine which date IDs will be removed
    const currentDateIds = new Set(
      historyState.state.dates.range.startDate && historyState.state.dates.range.endDate
        ? _generateDateItems(historyState.state.dates.range.startDate, historyState.state.dates.range.endDate).map(item => item.id)
        : []
    );

    const newDateIds = new Set(
      dateRange.startDate && dateRange.endDate
        ? _generateDateItems(dateRange.startDate, dateRange.endDate).map(item => item.id)
        : []
    );

    const removedDateIds = [...currentDateIds].filter(id => !newDateIds.has(id));
    const generatedDateItems =
      dateRange.startDate && dateRange.endDate ? _generateDateItems(dateRange.startDate, dateRange.endDate) : [];
    const shouldImportTaiwanHolidays =
      options.importTaiwanHolidays === true && isTaiwanHolidayRangeSupported(dateRange);

    // Update the date range
    updateState(prevState => {
      // Create newGroups by filtering out removed date IDs
      let newGroups = prevState.dates.groups.map(group => ({
        ...group,
        members: group.members.filter(memberId => !removedDateIds.includes(memberId))
      }));

      if (shouldImportTaiwanHolidays) {
        newGroups = replaceDateGroups(newGroups, buildTaiwanHolidayGroups(generatedDateItems, dateRange));
      }

      const nextState = {
        ...prevState,
        dates: {
          ...prevState.dates,
          range: dateRange,
          groups: newGroups
          // items will be auto-generated based on the new range
        }
      };
      return applyReferencesForIdDeletion(nextState, DataType.DATES, removedDateIds);
    });
  };

  const applyDataUpdate = (
    state: SchedulingState,
    dataType: DataType,
    newData: ItemGroupEditorPageData
  ): SchedulingState => {
    switch (dataType) {
      case DataType.DATES:
        return {
          ...state,
          dates: {
            ...state.dates,
            items: state.dates.items,
            groups: newData.groups
          }
        };
      case DataType.PEOPLE:
        return {
          ...state,
          people: newData
        };
      case DataType.SHIFT_TYPES:
        return {
          ...state,
          shiftTypes: newData
        };
    }
  };

  // Private helper function to update data based on dataType
  const updateData = (
    dataType: DataType,
    newData: ItemGroupEditorPageData,
    options?: { replaceLatestHistoryEntry?: boolean }
  ): void => {
    updateState(prevState => applyDataUpdate(prevState, dataType, newData), options);
  };

  // Reset to defaults
  const createNewState = () => {
    const newState = addAutoGeneratedToState(createDefaultState());
    setHistoryState(prevHistoryState => {
      const newHistoryState = addToHistory(prevHistoryState, newState);
      saveStateToStorage(newHistoryState);
      return newHistoryState;
    });
  };

  const addItem = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    id: string,
    groupIds: string[],
    description?: string
  ): void => {
    // Check if the ID is a reserved keyword
    if (isReservedKeyword(dataType, id)) {
      console.error(`Cannot add item with ID "${id}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    // Add the item
    const newItem = dataType === DataType.PEOPLE
      ? { id, description: description || '', history: [] }
      : { id, description: description || '' };
    const newItems = [...data.items, newItem];

    // If groupIds is provided, add the item to those groups
    const updatedGroups = data.groups.map(group => {
      if (!groupIds.includes(group.id)) {
        return group;
      }
      const allMembers = [...group.members, id];
      // Sort members based on updated items order
      const sortedMembers = newItems
        .filter(item => allMembers.includes(item.id))
        .map(item => item.id);
      if (allMembers.length !== sortedMembers.length) {
        console.error(`All members length ${allMembers.length} does not match sorted members length ${sortedMembers.length}. ${ERROR_SHOULD_NOT_HAPPEN}`);
        return group;
      }
      return {
        ...group,
        members: sortedMembers
      };
    });

    const newData = { items: newItems, groups: updatedGroups };

    updateData(dataType, newData);
  };

  const addGroup = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    id: string,
    memberIds: string[],
    description?: string
  ): void => {
    // Check if the ID is a reserved keyword
    if (isReservedKeyword(dataType, id)) {
      console.error(`Cannot add group with ID "${id}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    // Sort members based on items order
    const sortedMembers = data.items
      .filter(item => memberIds.includes(item.id))
      .map(item => item.id);

    if (memberIds.length !== sortedMembers.length) {
      console.error(`Member IDs length ${memberIds.length} does not match sorted members length ${sortedMembers.length}. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const newGroup = { id, members: sortedMembers, description: description || '' };
    const newGroups = [...data.groups, newGroup];

    const newData = { ...data, groups: newGroups };

    updateData(dataType, newData);
  };

  const applyPeopleHistoryForIdChange = (
    state: SchedulingState,
    dataType: DataType,
    oldId: string,
    newId: string
  ): SchedulingState => {
    if (dataType !== DataType.SHIFT_TYPES) return state;
    return {
      ...state,
      people: {
        ...state.people,
        items: state.people.items.map(person => ({
          ...person,
          history: person.history?.map(h => h === oldId ? newId : h) || []
        }))
      }
    };
  };

  const applyPeopleHistoryForIdDeletion = (
    state: SchedulingState,
    dataType: DataType,
    deletedIds: string[]
  ): SchedulingState => {
    if (dataType !== DataType.SHIFT_TYPES || deletedIds.length === 0) return state;

    const deletedIdSet = new Set(deletedIds);
    return {
      ...state,
      people: {
        ...state.people,
        items: state.people.items.map(person => {
          const history = person.history ?? [];
          const lastDeletedIndex = history.findLastIndex(shiftTypeId => deletedIdSet.has(shiftTypeId));
          return {
            ...person,
            history: lastDeletedIndex === -1 ? history : history.slice(lastDeletedIndex + 1)
          };
        })
      }
    };
  };

  // Unified function to update preferences when an ID changes
  const applyPreferencesForIdChange = (
    state: SchedulingState,
    dataType: DataType,
    oldId: string,
    newId: string
  ): SchedulingState => {
    const shiftTypeReqFieldMap = {
      [DataType.DATES]: 'date',
      [DataType.PEOPLE]: 'qualifiedPeople',
      [DataType.SHIFT_TYPES]: 'shiftType'
    };

    const shiftRequestFieldMap = {
      [DataType.DATES]: 'date',
      [DataType.PEOPLE]: 'person',
      [DataType.SHIFT_TYPES]: 'shiftType'
    };

    const shiftTypeSuccessionsFieldMap = {
      [DataType.DATES]: undefined,
      [DataType.PEOPLE]: 'person',
      [DataType.SHIFT_TYPES]: 'pattern'
    };

    const shiftCountFieldMap = {
      [DataType.DATES]: 'countDates',
      [DataType.PEOPLE]: 'person',
      [DataType.SHIFT_TYPES]: 'countShiftTypes'
    };

    const shiftAffinityFieldMap = {
      [DataType.DATES]: ['date'],
      [DataType.PEOPLE]: ['people1', 'people2'],
      [DataType.SHIFT_TYPES]: ['shiftTypes']
    };

    return {
      ...state,
      preferences: state.preferences.map(pref => {
        if (pref.type === SHIFT_TYPE_REQUIREMENT) {
          const fieldName = shiftTypeReqFieldMap[dataType] as keyof ShiftTypeRequirementsPreference;
          return {
            ...pref,
            [fieldName]: ((pref as ShiftTypeRequirementsPreference)[fieldName] as string[]).map(id => id === oldId ? newId : id)
          };
        } else if (pref.type === SHIFT_REQUEST) {
          const fieldName = shiftRequestFieldMap[dataType] as keyof ShiftRequestPreference;
          return {
            ...pref,
            [fieldName]: ((pref as ShiftRequestPreference)[fieldName] as string[]).map(id => id === oldId ? newId : id)
          };
        } else if (pref.type === SHIFT_TYPE_SUCCESSIONS) {
          if (shiftTypeSuccessionsFieldMap[dataType] === undefined) {
            return pref;
          }
          const fieldName = shiftTypeSuccessionsFieldMap[dataType] as keyof ShiftTypeSuccessionsPreference;
          return {
            ...pref,
            [fieldName]: ((pref as ShiftTypeSuccessionsPreference)[fieldName] as string[]).map(id => id === oldId ? newId : id)
          };
        } else if (pref.type === SHIFT_COUNT) {
          const fieldName = shiftCountFieldMap[dataType] as keyof ShiftCountPreference;
          const updatedPref: ShiftCountPreference = {
            ...pref,
            [fieldName]: ((pref as ShiftCountPreference)[fieldName] as string[]).map(id => id === oldId ? newId : id)
          };
          if (dataType === DataType.SHIFT_TYPES && updatedPref.countShiftTypeCoefficients) {
            updatedPref.countShiftTypeCoefficients = updatedPref.countShiftTypeCoefficients.map(([id, coefficient]) => [
              id === oldId ? newId : id,
              coefficient
            ]);
          }
          return updatedPref;
        } else if (pref.type === SHIFT_AFFINITY) {
          const fieldNames = shiftAffinityFieldMap[dataType];
          const updatedPref = { ...pref } as ShiftAffinityPreference;
          fieldNames.forEach(fieldName => {
            const key = fieldName as keyof ShiftAffinityPreference;
            const value = (pref as ShiftAffinityPreference)[key];
            if (Array.isArray(value)) {
              (updatedPref[key] as string[]) = value.map((id: string) => id === oldId ? newId : id);
            }
          });
          return updatedPref;
        }
        return pref;
      })
    };
  };

  // Unified function to update preferences when IDs are deleted
  const applyPreferencesForIdDeletion = (
    state: SchedulingState,
    dataType: DataType,
    deletedIds: string[]
  ): SchedulingState => {
    // Return early if no IDs to delete
    if (deletedIds.length === 0) {
      return state;
    }

    const deletedIdsSet = new Set(deletedIds);

    const shiftTypeReqFieldMap = {
      [DataType.DATES]: 'date',
      [DataType.PEOPLE]: 'qualifiedPeople',
      [DataType.SHIFT_TYPES]: 'shiftType'
    };

    const shiftRequestFieldMap = {
      [DataType.DATES]: 'date',
      [DataType.PEOPLE]: 'person',
      [DataType.SHIFT_TYPES]: 'shiftType'
    };

    const shiftTypeSuccessionsFieldMap = {
      [DataType.DATES]: undefined,
      [DataType.PEOPLE]: 'person',
      [DataType.SHIFT_TYPES]: 'pattern'
    };

    const shiftCountFieldMap = {
      [DataType.DATES]: 'countDates',
      [DataType.PEOPLE]: 'person',
      [DataType.SHIFT_TYPES]: 'countShiftTypes'
    };

    const shiftAffinityFieldMap = {
      [DataType.DATES]: ['date'],
      [DataType.PEOPLE]: ['people1', 'people2'],
      [DataType.SHIFT_TYPES]: ['shiftTypes']
    };

    const preferences = state.preferences
      // First, filter out the deleted IDs from array fields and remove matching single-value preferences
      .map(pref => {
        if (pref.type === SHIFT_TYPE_REQUIREMENT) {
          const fieldName = shiftTypeReqFieldMap[dataType] as keyof ShiftTypeRequirementsPreference;
          return {
            ...pref,
            [fieldName]: ((pref as ShiftTypeRequirementsPreference)[fieldName] as string[]).filter(id => !deletedIdsSet.has(id))
          };
        } else if (pref.type === SHIFT_REQUEST) {
          const fieldName = shiftRequestFieldMap[dataType] as keyof ShiftRequestPreference;
          return {
            ...pref,
            [fieldName]: ((pref as ShiftRequestPreference)[fieldName] as string[]).filter(id => !deletedIdsSet.has(id))
          };
        } else if (pref.type === SHIFT_TYPE_SUCCESSIONS) {
          if (shiftTypeSuccessionsFieldMap[dataType] === undefined) {
            return pref;
          }
          const fieldName = shiftTypeSuccessionsFieldMap[dataType] as keyof ShiftTypeSuccessionsPreference;
          return {
            ...pref,
            [fieldName]: ((pref as ShiftTypeSuccessionsPreference)[fieldName] as string[]).filter(id => !deletedIdsSet.has(id))
          };
        } else if (pref.type === SHIFT_COUNT) {
          const fieldName = shiftCountFieldMap[dataType] as keyof ShiftCountPreference;
          const updatedPref: ShiftCountPreference = {
            ...pref,
            [fieldName]: ((pref as ShiftCountPreference)[fieldName] as string[]).filter(id => !deletedIdsSet.has(id))
          };
          if (dataType === DataType.SHIFT_TYPES && updatedPref.countShiftTypeCoefficients) {
            updatedPref.countShiftTypeCoefficients = updatedPref.countShiftTypeCoefficients.filter(
              ([id]) => !deletedIdsSet.has(id)
            );
          }
          return updatedPref;
        } else if (pref.type === SHIFT_AFFINITY) {
          const fieldNames = shiftAffinityFieldMap[dataType];
          const updatedPref = { ...pref } as ShiftAffinityPreference;
          fieldNames.forEach(fieldName => {
            const key = fieldName as keyof ShiftAffinityPreference;
            const value = (pref as ShiftAffinityPreference)[key];
            if (Array.isArray(value)) {
              (updatedPref[key] as string[]) = value.filter(id => !deletedIdsSet.has(id));
            }
          });
          return updatedPref;
        }
        return pref;
      })
      // Second, remove preferences with empty required fields
      .filter(pref => {
        if (pref.type === SHIFT_TYPE_REQUIREMENT) {
          return (pref as ShiftTypeRequirementsPreference).shiftType.length > 0;
        } else if (pref.type === SHIFT_REQUEST) {
          return (pref as ShiftRequestPreference).person.length > 0 &&
            (pref as ShiftRequestPreference).date.length > 0 &&
            (pref as ShiftRequestPreference).shiftType.length > 0;
        } else if (pref.type === SHIFT_TYPE_SUCCESSIONS) {
          return (pref as ShiftTypeSuccessionsPreference).person.length > 0 &&
            (pref as ShiftTypeSuccessionsPreference).pattern.length > 0;
        } else if (pref.type === SHIFT_COUNT) {
          return (pref as ShiftCountPreference).person.length > 0 &&
            (pref as ShiftCountPreference).countDates.length > 0 &&
            (pref as ShiftCountPreference).countShiftTypes.length > 0;
        } else if (pref.type === SHIFT_AFFINITY) {
          return (pref as ShiftAffinityPreference).date.length > 0 &&
            (pref as ShiftAffinityPreference).people1.length > 0 &&
            (pref as ShiftAffinityPreference).people2.length > 0 &&
            (pref as ShiftAffinityPreference).shiftTypes.length > 0;
        }
        return true;
      });

    return {
      ...state,
      preferences
    };
  };

  const applyExportLayoutForIdDeletion = (
    state: SchedulingState,
    dataType: DataType,
    deletedIds: string[]
  ): SchedulingState => {
    if (deletedIds.length === 0) {
      return state;
    }

    const deletedIdsSet = new Set(deletedIds);
    const filterIds = (ids: string[]) => ids.filter(id => !deletedIdsSet.has(id));

    if (!state.export) {
      return state;
    }

    return {
      ...state,
      export: {
        ...state.export,
        formatting: state.export?.formatting
          ?.map(rule => {
            if (dataType === DataType.PEOPLE && 'people' in rule) {
              return { ...rule, people: filterIds(rule.people) };
            }
            if (dataType === DataType.DATES && 'dates' in rule) {
              return { ...rule, dates: filterIds(rule.dates) };
            }
            if (dataType === DataType.SHIFT_TYPES && 'shiftTypes' in rule) {
              return { ...rule, shiftTypes: filterIds(rule.shiftTypes) };
            }
            return rule;
          })
          .filter(rule => {
            if ('people' in rule && rule.people.length === 0) return false;
            if ('dates' in rule && rule.dates.length === 0) return false;
            if ('shiftTypes' in rule && rule.shiftTypes.length === 0) return false;
            return true;
          }),
        extraColumns: state.export?.extraColumns
          ?.map(rule => {
            if (dataType === DataType.DATES) {
              return { ...rule, countDates: filterIds(rule.countDates) };
            }
            if (dataType === DataType.SHIFT_TYPES) {
              return { ...rule, countShiftTypes: filterIds(rule.countShiftTypes) };
            }
            return rule;
          })
          .filter(rule => rule.countDates.length > 0 && rule.countShiftTypes.length > 0),
        extraRows: state.export?.extraRows
          ?.map(rule => {
            if (dataType === DataType.PEOPLE) {
              return { ...rule, countPeople: filterIds(rule.countPeople) };
            }
            if (dataType === DataType.SHIFT_TYPES) {
              return { ...rule, countShiftTypes: filterIds(rule.countShiftTypes) };
            }
            return rule;
          })
          .filter(rule => rule.countPeople.length > 0 && rule.countShiftTypes.length > 0)
      }
    };
  };

  const applyExportLayoutForIdChange = (
    state: SchedulingState,
    dataType: DataType,
    oldId: string,
    newId: string
  ): SchedulingState => {
    const renameId = (id: string) => id === oldId ? newId : id;
    const renameIds = (ids: string[]) => ids.map(renameId);

    if (!state.export) {
      return state;
    }

    return {
      ...state,
      export: {
        ...state.export,
        formatting: state.export.formatting?.map(rule => {
          if (dataType === DataType.PEOPLE && 'people' in rule) {
            return { ...rule, people: renameIds(rule.people) };
          }
          if (dataType === DataType.DATES && 'dates' in rule) {
            return { ...rule, dates: renameIds(rule.dates) };
          }
          if (dataType === DataType.SHIFT_TYPES && 'shiftTypes' in rule) {
            return { ...rule, shiftTypes: renameIds(rule.shiftTypes) };
          }
          return rule;
        }),
        extraColumns: state.export.extraColumns?.map(rule => {
          if (dataType === DataType.DATES) {
            return { ...rule, countDates: renameIds(rule.countDates) };
          }
          if (dataType === DataType.SHIFT_TYPES) {
            return { ...rule, countShiftTypes: renameIds(rule.countShiftTypes) };
          }
          return rule;
        }),
        extraRows: state.export.extraRows?.map(rule => {
          if (dataType === DataType.PEOPLE) {
            return { ...rule, countPeople: renameIds(rule.countPeople) };
          }
          if (dataType === DataType.SHIFT_TYPES) {
            return { ...rule, countShiftTypes: renameIds(rule.countShiftTypes) };
          }
          return rule;
        })
      }
    };
  };

  const applyReferencesForIdChange = (
    state: SchedulingState,
    dataType: DataType,
    oldId: string,
    newId: string
  ): SchedulingState => {
    let nextState = applyPeopleHistoryForIdChange(state, dataType, oldId, newId);
    nextState = applyPreferencesForIdChange(nextState, dataType, oldId, newId);
    nextState = applyExportLayoutForIdChange(nextState, dataType, oldId, newId);
    return nextState;
  };

  const applyReferencesForIdDeletion = (
    state: SchedulingState,
    dataType: DataType,
    deletedIds: string[]
  ): SchedulingState => {
    let nextState = applyPeopleHistoryForIdDeletion(state, dataType, deletedIds);
    nextState = applyPreferencesForIdDeletion(nextState, dataType, deletedIds);
    nextState = applyExportLayoutForIdDeletion(nextState, dataType, deletedIds);
    return nextState;
  };

  const updateItem = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    oldId: string,
    newId: string,
    groupIds?: string[],
    description?: string
  ): void => {
    if (dataType === DataType.DATES && data.items.some(item => item.id === oldId && item.isAutoGenerated)) {
      console.error(`Cannot rename derived date item ID "${oldId}" to "${newId}". ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    // Check if the new ID is a reserved keyword
    if (isReservedKeyword(dataType, newId)) {
      console.error(`Cannot update item to ID "${newId}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    // First update the item's ID and description
    const updatedItems = data.items.map(item =>
      item.id === oldId
        ? {
            ...item,
            id: newId,
            description: description !== undefined ? description : item.description
          }
        : item
    );

    // Always update group memberships to reflect the new ID
    const updatedGroups = data.groups.map(group => {
      // Get current members excluding the edited item
      const otherMembers = group.members.filter(id => id !== oldId);

      // Add the item if they should be in this group
      const allMembers = groupIds
        ? (groupIds.includes(group.id) ? [...otherMembers, newId] : otherMembers)
        : (group.members.includes(oldId) ? [...otherMembers, newId] : otherMembers);

      // Sort members based on updated items order
      const sortedMembers = updatedItems
        .filter(item => allMembers.includes(item.id))
        .map(item => item.id);

      if (allMembers.length !== sortedMembers.length) {
        console.error(`All members length ${allMembers.length} does not match sorted members length ${sortedMembers.length}. ${ERROR_SHOULD_NOT_HAPPEN}`);
        return group;
      }

      return {
        ...group,
        members: sortedMembers
      };
    });

    const newData = { items: updatedItems, groups: updatedGroups };

    updateState(prevState => {
      const nextState = applyDataUpdate(prevState, dataType, newData);
      return applyReferencesForIdChange(nextState, dataType, oldId, newId);
    });
  };

  const updateGroup = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    oldId: string,
    newId: string,
    members?: string[],
    description?: string
  ): void => {
    // Check if the new ID is a reserved keyword
    if (isReservedKeyword(dataType, newId)) {
      console.error(`Cannot update group to ID "${newId}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const group = data.groups.find(g => g.id === oldId);
    if (!group) {
      console.error(`Group with ID ${oldId} not found. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    // Sort members based on items order
    const sortedMembers = members
      ? data.items
          .filter(item => members.includes(item.id))
          .map(item => item.id)
      : group.members;

    if (members && members.length !== sortedMembers.length) {
      console.error(`Members length ${members.length} does not match sorted members length ${sortedMembers.length}. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const newGroups = data.groups.map(g =>
      g.id === oldId
        ? {
            ...g,
            id: newId,
            members: sortedMembers,
            description: description !== undefined ? description : g.description
          }
        : g
    );

    const newData = { ...data, groups: newGroups };

    updateState(prevState => {
      const nextState = applyDataUpdate(prevState, dataType, newData);
      return applyReferencesForIdChange(nextState, dataType, oldId, newId);
    });
  };

  const deleteItem = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    id: string
  ): void => {
    if (isReservedKeyword(dataType, id)) {
      console.error(`Cannot delete item with ID "${id}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const newItems = data.items.filter(item => item.id !== id);
    const newGroups = data.groups.map(group => ({
      ...group,
      members: group.members.filter(memberId => memberId !== id)
    }));

    const newData = { items: newItems, groups: newGroups };

    updateState(prevState => {
      const nextState = applyDataUpdate(prevState, dataType, newData);
      return applyReferencesForIdDeletion(nextState, dataType, [id]);
    });
  };

  const deleteGroup = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    id: string
  ): void => {
    if (isReservedKeyword(dataType, id)) {
      console.error(`Cannot delete group with ID "${id}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const newGroups = data.groups.filter(g => g.id !== id);
    const newData = { ...data, groups: newGroups };

    updateState(prevState => {
      const nextState = applyDataUpdate(prevState, dataType, newData);
      return applyReferencesForIdDeletion(nextState, dataType, [id]);
    });
  };

  const removeItemFromGroup = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    itemId: string,
    groupId: string
  ): void => {
    if (isReservedKeyword(dataType, groupId)) {
      console.error(`Cannot remove item from group with ID "${groupId}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const newGroups = data.groups.map(group =>
      group.id === groupId
        ? { ...group, members: group.members.filter(id => id !== itemId) }
        : group
    );

    const newData = { ...data, groups: newGroups };

    updateData(dataType, newData);
  };

  const reorderItems = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    reorderedItems: Item[]
  ): void => {
    // Sort group members based on items order
    const updatedGroups = data.groups.map(group => ({
      ...group,
      members: reorderedItems
        .filter(item => group.members.includes(item.id))
        .map(item => item.id)
    }));

    const newData = { items: reorderedItems, groups: updatedGroups };

    updateData(dataType, newData);
  };

  const reorderGroups = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    newGroups: Group[]
  ): void => {
    const newData = { ...data, groups: newGroups };

    updateData(dataType, newData);
  };

  const addPersonHistory = (
    personId: string,
    shiftTypeId: string,
    options: HistoryMutationOptions = {}
  ) => {
    updateState(prevState => {
      const updatedPeople = {
        ...prevState.people,
        items: prevState.people.items.map(person => {
          if (person.id === personId) {
            const newHistory = [shiftTypeId, ...person.history!];
            return { ...person, history: newHistory };
          }
          return person;
        })
      };
      return { ...prevState, people: updatedPeople };
    }, options);
  };

  const updatePersonHistory = (
    personId: string,
    position: number,
    shiftTypeId?: string,
    options: HistoryMutationOptions = {}
  ) => {
    updateState(prevState => {
      const updatedPeople = {
        ...prevState.people,
        items: prevState.people.items.map(person => {
          if (person.id === personId) {
            if (shiftTypeId !== undefined) {
              // Update the specific position
              const newHistory = [...person.history!];
              if (position >= newHistory.length) {
                console.error(`Position ${position} is out of bounds for person ${personId}. ${ERROR_SHOULD_NOT_HAPPEN}`);
                return person;
              }
              newHistory[position] = shiftTypeId;
              return { ...person, history: newHistory };
            } else {
              // Clear all history entries before the specified position
              const newHistory = person.history!.slice(position + 1);
              return { ...person, history: newHistory };
            }
          }
          return person;
        })
      };
      return { ...prevState, people: updatedPeople };
    }, options);
  };

  // Helper functions to work with flattened preferences
  const getPreferencesByType = <T extends Preference>(type: string): T[] => {
    return historyState.state.preferences.filter(pref => pref.type === type) as T[];
  };

  const updatePreferences = (
    newPreferences: Preference[],
    options: HistoryMutationOptions = {}
  ) => {
    updateState(prevState => ({
      ...prevState,
      preferences: normalizePreferencesOrder(newPreferences, prevState)
    }), options);
  };

  const updatePreferencesByType = <T extends Preference>(
    type: string,
    newPreferences: T[],
    options: HistoryMutationOptions = {}
  ) => {
    const otherPreferences = historyState.state.preferences.filter(pref => pref.type !== type);
    if (type === SHIFT_REQUEST) {
      const combinedDateEntries = getOrderedEntries(historyState.state.dates);
      // Sort preferences by person, shift type, weight.
      newPreferences = sortShiftRequestsByEntityOrder(newPreferences as ShiftRequestPreference[], historyState.state) as T[];
      // Sort each preference date array
      (newPreferences as ShiftRequestPreference[]).forEach(pref => {
        if (pref.person.length !== 1) {
          console.error(`A single shift request corresponds to multiple people. ${ERROR_SHOULD_NOT_HAPPEN}`);
          return pref;
        }
        if (pref.shiftType.length !== 1) {
          console.error(`A single shift request corresponds to multiple shift types. ${ERROR_SHOULD_NOT_HAPPEN}`);
          return pref;
        }
        if (pref.date.length === 0) {
          console.error(`A single shift request corresponds to no dates. ${ERROR_SHOULD_NOT_HAPPEN}`);
          return pref;
        }
        pref.date.sort((a, b) => {
          const dateIndexA = combinedDateEntries.findIndex(p => p.id === a);
          const dateIndexB = combinedDateEntries.findIndex(p => p.id === b);
          return dateIndexA - dateIndexB;
        });
      });
    }
    // Sort preferences by type after updating
    const updatedPreferences = normalizePreferencesOrder([...otherPreferences, ...newPreferences], historyState.state);
    updatePreferences(updatedPreferences, options);
  };

  const updateExportFormatting = (formatting?: ExportFormatting[]) => {
    updateState(prevState => ({
      ...prevState,
      export: {
        ...(prevState.export ?? generateExportLayoutConfig(prevState.shiftTypes, prevState.dates.groups)),
        formatting: normalizeExportFormattingOrder(formatting, prevState)
      }
    }));
  };

  const updateExportExtraColumns = (extraColumns?: ExportExtraColumn[]) => {
    updateState(prevState => ({
      ...prevState,
      export: {
        ...(prevState.export ?? generateExportLayoutConfig(prevState.shiftTypes, prevState.dates.groups)),
        extraColumns: normalizeExportExtraColumnsOrder(extraColumns, prevState)
      }
    }));
  };

  const updateExportExtraRows = (extraRows?: ExportExtraRow[]) => {
    updateState(prevState => ({
      ...prevState,
      export: {
        ...(prevState.export ?? generateExportLayoutConfig(prevState.shiftTypes, prevState.dates.groups)),
        extraRows: normalizeExportExtraRowsOrder(extraRows, prevState)
      }
    }));
  };

  const updateExportConfig = (exportConfig?: ExportConfig) => {
    updateState(prevState => ({
      ...prevState,
      export: normalizeExportConfigOrder(exportConfig, prevState)
    }));
  };

  const loadFromYaml = (yamlData: unknown) => {
    // Create new state from YAML data without validation
    // TODO: Add validation

    // Cast to partial SchedulingState to access properties safely
    const data = yamlData as Partial<SchedulingState> & {
      dates?: Partial<SchedulingState['dates']> & {
        range?: Partial<DateRange>;
      };
      people?: Partial<SchedulingState['people']>;
      shiftTypes?: Partial<SchedulingState['shiftTypes']>;
      export?: Partial<ExportConfig>;
    };

    const newState: SchedulingState = addAutoGeneratedToState({
      apiVersion: data.apiVersion || API_VERSION,
      description: data.description || '',
      dates: {
        range: data.dates?.range ? {
          startDate: data.dates.range.startDate ? new Date(data.dates.range.startDate) : undefined,
          endDate: data.dates.range.endDate ? new Date(data.dates.range.endDate) : undefined,
        } : { startDate: undefined, endDate: undefined },
        items: data.dates?.items || [],
        groups: data.dates?.groups || []
      },
      people: {
        items: data.people?.items || [],
        groups: data.people?.groups || []
      },
      shiftTypes: data.shiftTypes || { items: [], groups: [] },
      preferences: data.preferences || [],
      ...(data.export ? { export: data.export } : {})
    });

    // If any ID is a number, convert it to a string
    const convertIdsToString = (arr: { id: number | string }[]) => {
      arr.forEach(obj => {
        if (typeof obj.id === 'number') obj.id = String(obj.id);
      });
    };
    convertIdsToString(newState.dates.items);
    convertIdsToString(newState.dates.groups);
    convertIdsToString(newState.people.items);
    convertIdsToString(newState.people.groups);
    convertIdsToString(newState.shiftTypes.items);
    convertIdsToString(newState.shiftTypes.groups);
    const convertArrayIdsToString = (arr: (number | string)[], isDate: boolean = false) => {
      if (!Array.isArray(arr)) return;
      for (let i = 0; i < arr.length; i++) {
        if (typeof arr[i] === 'number') {
          if (isDate) {
            arr[i] = arr[i].toString().padStart(2, '0');
          } else {
            arr[i] = arr[i].toString();
          }
        }
      }
    };
    newState.preferences.forEach(pref => {
      // Compatibility: Add missing date field for those not required by the backend solver.
      if (pref.type === SHIFT_TYPE_REQUIREMENT && !('date' in pref)) {
        (pref as ShiftTypeRequirementsPreference).date = [ALL];
      } else if (pref.type === SHIFT_TYPE_SUCCESSIONS && !('date' in pref)) {
        (pref as ShiftTypeSuccessionsPreference).date = [ALL];
      }

      // Type-safe property access with proper type guards
      if ('shiftType' in pref && pref.shiftType) {
        convertArrayIdsToString(pref.shiftType);
      }
      if ('qualifiedPeople' in pref && pref.qualifiedPeople) {
        convertArrayIdsToString(pref.qualifiedPeople);
      }
      if ('date' in pref && pref.date) {
        convertArrayIdsToString(pref.date, true);
      }
      if ('person' in pref && pref.person) {
        convertArrayIdsToString(pref.person);
      }
      if ('pattern' in pref && pref.pattern) {
        convertArrayIdsToString(pref.pattern);
      }
      if ('countDates' in pref && pref.countDates) {
        convertArrayIdsToString(pref.countDates, true);
      }
      if ('countShiftTypes' in pref && pref.countShiftTypes) {
        convertArrayIdsToString(pref.countShiftTypes);
      }
      if (pref.type === SHIFT_COUNT && pref.countShiftTypeCoefficients) {
        pref.countShiftTypeCoefficients = pref.countShiftTypeCoefficients.map(([id, coefficient]) => [
          String(id),
          coefficient
        ]);
      }
      if ('people1' in pref && pref.people1) {
        convertArrayIdsToString(pref.people1);
      }
      if ('people2' in pref && pref.people2) {
        convertArrayIdsToString(pref.people2);
      }
      if ('shiftTypes' in pref && pref.shiftTypes) {
        convertArrayIdsToString(pref.shiftTypes);
      }
    });
    newState.export?.formatting?.forEach(rule => {
      if ('people' in rule) {
        convertArrayIdsToString(rule.people);
      }
      if ('dates' in rule) {
        convertArrayIdsToString(rule.dates, true);
      }
      if ('shiftTypes' in rule) {
        convertArrayIdsToString(rule.shiftTypes);
      }
    });
    newState.export?.extraColumns?.forEach(rule => {
      convertArrayIdsToString(rule.countShiftTypes);
      convertArrayIdsToString(rule.countDates, true);
    });
    newState.export?.extraRows?.forEach(rule => {
      convertArrayIdsToString(rule.countShiftTypes);
      convertArrayIdsToString(rule.countPeople);
    });
    newState.preferences = normalizePreferencesOrder(newState.preferences, newState);
    newState.export = normalizeExportConfigOrder(newState.export, newState);

    // Add to history and update state
    setHistoryState(prevHistoryState => {
      const newHistoryState = addToHistory(prevHistoryState, newState);
      saveStateToStorage(newHistoryState);
      return newHistoryState;
    });
  };

  const effectiveExportData =
    historyState.state.export ?? generateExportLayoutConfig(historyState.state.shiftTypes, historyState.state.dates.groups);

  return {
    updateDateRange,
    apiVersionData: historyState.state.apiVersion,
    descriptionData: historyState.state.description,
    dateData: historyState.state.dates,
    peopleData: historyState.state.people,
    shiftTypeData: historyState.state.shiftTypes,
    preferences: historyState.state.preferences, // Flattened preferences API
    exportData: historyState.state.export,
    effectiveExportData,
    updatePreferences,
    updatePreferencesByType,
    getPreferencesByType,
    updateExportFormatting,
    updateExportExtraColumns,
    updateExportExtraRows,
    updateExportConfig,

    addPersonHistory,
    updatePersonHistory,
    createNewState,
    loadFromYaml,
    filterAutoGeneratedState,
    undo,
    redo,
    // Helper functions
    addItem,
    addGroup,
    updateItem,
    updateGroup,
    deleteItem,
    deleteGroup,
    removeItemFromGroup,
    reorderItems,
    reorderGroups,
  };
}
