/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// The shift type management page for Tab "3. Shift Types"
'use client';

import { useState } from 'react';
import { useSchedulingData } from '@/hooks/useSchedulingData';
import ItemGroupEditorPage from '@/components/ItemGroupEditorPage';
import { Mode } from '@/constants/modes';
import { DataType } from '@/types/scheduling';
import { filterAutoGenerated } from '@/utils/keywords';
import { DOCUMENTATION_URLS } from '@/constants/urls';

export default function ShiftTypePage() {
  const {
    shiftTypeData,
    // Get functions to pass as props
    addItem,
    addGroup,
    duplicateItem,
    duplicateGroup,
    updateItem,
    updateGroup,
    deleteItem,
    deleteGroup,
    removeItemFromGroup,
    reorderItems,
    reorderGroups,
  } = useSchedulingData();

  const [mode, setMode] = useState<Mode>(Mode.NORMAL);

  return (
    <ItemGroupEditorPage
      title="Shift Type Management"
      documentationHref={DOCUMENTATION_URLS.shiftTypes}
      data={shiftTypeData}
      dataType={DataType.SHIFT_TYPES}
      mode={mode}
      setMode={setMode}
      addItem={addItem}
      addGroup={addGroup}
      duplicateItem={duplicateItem}
      duplicateGroup={duplicateGroup}
      updateItem={updateItem}
      updateGroup={updateGroup}
      deleteItem={deleteItem}
      deleteGroup={deleteGroup}
      removeItemFromGroup={removeItemFromGroup}
      reorderItems={reorderItems}
      reorderGroups={reorderGroups}
      filterItemGroups={filterAutoGenerated}
    />
  );
}
