/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import ShiftTypeRequirementsPage from '@/app/shift-type-requirements/page';

const mockUseSchedulingData = vi.hoisted(() => vi.fn());

vi.mock('@/hooks/useSchedulingData', () => ({
  useSchedulingData: mockUseSchedulingData,
}));

describe('ShiftTypeRequirementsPage', () => {
  const updatePreferencesByType = vi.fn();

  beforeEach(() => {
    updatePreferencesByType.mockReset();
    mockUseSchedulingData.mockReturnValue({
      dateData: {
        range: {
          startDate: new Date('2026-01-01T12:00:00.000Z'),
          endDate: new Date('2026-01-01T12:00:00.000Z'),
        },
        items: [{ id: '01', description: 'Jan 1' }],
        groups: [{ id: 'ALL', members: ['01'], description: 'All dates' }],
      },
      peopleData: {
        items: [{ id: 'P1', description: 'Person 1', history: [] }],
        groups: [{ id: 'ALL', members: ['P1'], description: 'All people' }],
      },
      shiftTypeData: {
        items: [
          { id: 'OFF', description: 'Off shift type', isAutoGenerated: true },
          { id: 'D', description: 'Day' },
        ],
        groups: [{ id: 'ALL', members: ['OFF', 'D'], description: 'All shift types', isAutoGenerated: true }],
      },
      getPreferencesByType: vi.fn(() => []),
      updatePreferencesByType,
    });
  });

  it('does not show OFF in the shift type requirement checkbox list', async () => {
    const user = userEvent.setup();

    render(<ShiftTypeRequirementsPage />);

    await user.click(screen.getByRole('button', { name: /add requirement/i }));

    expect(screen.getByRole('checkbox', { name: 'D' })).toBeInTheDocument();
    expect(screen.queryByRole('checkbox', { name: 'OFF' })).not.toBeInTheDocument();
  });

  it('warns when a date and shift type pair has no requirement coverage', () => {
    render(<ShiftTypeRequirementsPage />);

    expect(screen.getByText('Requirement coverage warnings')).toBeInTheDocument();
    expect(screen.getByText(/Undefined staffing requirements: 1 date\/shift type pairs have no requirement/)).toBeInTheDocument();
    expect(screen.getAllByText((_, element) => element?.tagName === 'LI' && element.textContent === 'D: ALL')).toHaveLength(1);
  });

  it('expands undefined dates when no exact date group matches', () => {
    mockUseSchedulingData.mockReturnValue({
      dateData: {
        range: {
          startDate: new Date('2026-01-01T12:00:00.000Z'),
          endDate: new Date('2026-01-02T12:00:00.000Z'),
        },
        items: [
          { id: '01', description: 'Jan 1' },
          { id: '02', description: 'Jan 2' },
        ],
        groups: [{ id: 'FIRST_DAY', members: ['01'], description: 'First day' }],
      },
      peopleData: {
        items: [{ id: 'P1', description: 'Person 1', history: [] }],
        groups: [{ id: 'ALL', members: ['P1'], description: 'All people' }],
      },
      shiftTypeData: {
        items: [
          { id: 'OFF', description: 'Off shift type', isAutoGenerated: true },
          { id: 'D', description: 'Day' },
        ],
        groups: [{ id: 'ALL', members: ['OFF', 'D'], description: 'All shift types', isAutoGenerated: true }],
      },
      getPreferencesByType: vi.fn(() => []),
      updatePreferencesByType,
    });

    render(<ShiftTypeRequirementsPage />);

    expect(screen.getByText(/Undefined staffing requirements: 2 date\/shift type pairs have no requirement/)).toBeInTheDocument();
    expect(screen.getAllByText((_, element) => element?.tagName === 'LI' && element.textContent === 'D: 01, 02')).toHaveLength(1);
  });

  it('warns when requirements duplicate expanded date and shift type coverage', () => {
    mockUseSchedulingData.mockReturnValue({
      dateData: {
        range: {
          startDate: new Date('2026-01-01T12:00:00.000Z'),
          endDate: new Date('2026-01-01T12:00:00.000Z'),
        },
        items: [{ id: '01', description: 'Jan 1' }],
        groups: [{ id: 'ALL', members: ['01'], description: 'All dates' }],
      },
      peopleData: {
        items: [{ id: 'P1', description: 'Person 1', history: [] }],
        groups: [{ id: 'ALL', members: ['P1'], description: 'All people' }],
      },
      shiftTypeData: {
        items: [
          { id: 'OFF', description: 'Off shift type', isAutoGenerated: true },
          { id: 'D', description: 'Day' },
        ],
        groups: [{ id: 'ALL', members: ['OFF', 'D'], description: 'All shift types', isAutoGenerated: true }],
      },
      getPreferencesByType: vi.fn(() => [
        {
          type: 'shift type requirement',
          shiftType: ['ALL'],
          requiredNumPeople: 1,
          qualifiedPeople: ['P1'],
          date: ['ALL'],
          weight: -1,
        },
        {
          type: 'shift type requirement',
          shiftType: ['D'],
          requiredNumPeople: 1,
          qualifiedPeople: ['P1'],
          date: ['01'],
          weight: -1,
        },
      ]),
      updatePreferencesByType,
    });

    render(<ShiftTypeRequirementsPage />);

    expect(screen.getByText('Requirement coverage warnings')).toBeInTheDocument();
    expect(screen.getByText(/Duplicate staffing requirements: 1 date\/shift type pairs are covered by more than one requirement/)).toBeInTheDocument();
    expect(screen.getByText('01 / D (requirements 1 and 2)')).toBeInTheDocument();
  });

  it('hides weight when preferred number of people equals required number and saves the default weight', async () => {
    const user = userEvent.setup();

    render(<ShiftTypeRequirementsPage />);

    await user.click(screen.getByRole('button', { name: /add requirement/i }));

    expect(screen.getByText('Weight is not needed when the preferred number of people equals the required number.')).toBeInTheDocument();
    expect(screen.queryByPlaceholderText('e.g., -1, -10, ∞')).not.toBeInTheDocument();

    await user.click(screen.getByRole('checkbox', { name: 'D' }));
    await user.click(screen.getByRole('checkbox', { name: 'P1' }));
    await user.click(screen.getByRole('checkbox', { name: '01' }));
    await user.click(screen.getByRole('button', { name: 'Add' }));

    expect(updatePreferencesByType).toHaveBeenCalledOnce();
    expect(updatePreferencesByType.mock.calls[0][1][0]).toMatchObject({
      preferredNumPeople: undefined,
      weight: -1,
    });
  });

  it('shows weight when preferred number of people is higher than required number', async () => {
    const user = userEvent.setup();

    render(<ShiftTypeRequirementsPage />);

    await user.click(screen.getByRole('button', { name: /add requirement/i }));
    const preferredNumPeopleInput = screen.getAllByRole('spinbutton')[1];
    await user.clear(preferredNumPeopleInput);
    await user.type(preferredNumPeopleInput, '2');

    expect(screen.queryByText('Weight is not needed when the preferred number of people equals the required number.')).not.toBeInTheDocument();
    expect(screen.getByPlaceholderText('e.g., -1, -10, ∞')).toBeInTheDocument();
  });
});
