/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import ShiftTypeRequirementsPage from '@/app/shift-type-requirements/page';

const mockUseSchedulingData = vi.hoisted(() => vi.fn());

vi.mock('@/hooks/useSchedulingData', () => ({
  useSchedulingData: mockUseSchedulingData,
}));

describe('ShiftTypeRequirementsPage', () => {
  beforeEach(() => {
    mockUseSchedulingData.mockReturnValue({
      dateData: {
        range: {
          startDate: new Date('2026-01-01T12:00:00.000Z'),
          endDate: new Date('2026-01-01T12:00:00.000Z'),
        },
        items: [{ id: '01', description: 'Jan 1' }],
        groups: [{ id: 'ALL', members: ['01'], description: 'All dates' }],
      },
      peopleData: {
        items: [{ id: 'P1', description: 'Person 1', history: [] }],
        groups: [{ id: 'ALL', members: ['P1'], description: 'All people' }],
      },
      shiftTypeData: {
        items: [
          { id: 'OFF', description: 'Off shift type', isAutoGenerated: true },
          { id: 'D', description: 'Day' },
        ],
        groups: [{ id: 'ALL', members: ['OFF', 'D'], description: 'All shift types', isAutoGenerated: true }],
      },
      getPreferencesByType: vi.fn(() => []),
      updatePreferencesByType: vi.fn(),
    });
  });

  it('does not show OFF in the shift type requirement checkbox list', async () => {
    const user = userEvent.setup();

    render(<ShiftTypeRequirementsPage />);

    await user.click(screen.getByRole('button', { name: /add requirement/i }));

    expect(screen.getByRole('checkbox', { name: 'D' })).toBeInTheDocument();
    expect(screen.queryByRole('checkbox', { name: 'OFF' })).not.toBeInTheDocument();
  });
});
