/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import ExperimentalAiPage from './page';

const mockCreateSession = vi.hoisted(() => vi.fn());
const mockGetCapabilities = vi.hoisted(() => vi.fn());
const mockStreamMessage = vi.hoisted(() => vi.fn());
const mockGenerateYaml = vi.hoisted(() => vi.fn(() => 'description: current schedule\n'));
const mockApproveProposal = vi.hoisted(() => vi.fn());
const mockRejectProposal = vi.hoisted(() => vi.fn());
const mockUpdateSessionSchedule = vi.hoisted(() => vi.fn());
const mockLoadFromYaml = vi.hoisted(() => vi.fn());
const mockUseTabSwitchWarning = vi.hoisted(() => vi.fn());
const MockAiStaleTurnError = vi.hoisted(() => class AiStaleTurnError extends Error {});

vi.mock('./aiClient', () => ({
  AiStaleTurnError: MockAiStaleTurnError,
  LOCAL_AI_API_URL: 'http://localhost:8001',
  PRODUCTION_AI_API_URL: 'https://api.nursescheduling.org/ai',
  createSession: mockCreateSession,
  getAiBaseUrl: () => '/ai',
  getCapabilities: mockGetCapabilities,
  normalizeAiEndpoint: (endpoint: string) => {
    const trimmed = endpoint.trim().replace(/\/+$/, '');
    if (!trimmed) return '';
    return /^[a-z]+:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}`;
  },
  streamMessage: mockStreamMessage,
  approveProposal: mockApproveProposal,
  rejectProposal: mockRejectProposal,
  updateSessionSchedule: mockUpdateSessionSchedule,
}));

vi.mock('@/utils/yamlGenerator', () => ({
  generateYamlFromState: mockGenerateYaml,
}));

vi.mock('@/hooks/useSchedulingData', () => ({
  useSchedulingData: () => ({
    apiVersionData: 'alpha',
    descriptionData: 'current schedule',
    dateData: { items: [], groups: [], range: {} },
    peopleData: { items: [], groups: [] },
    shiftTypeData: { items: [], groups: [] },
    preferences: [],
    exportData: undefined,
    filterAutoGeneratedState: (state: unknown) => state,
    loadFromYaml: mockLoadFromYaml,
  }),
}));

vi.mock('@/utils/unsavedEditingState', () => ({
  useTabSwitchWarning: mockUseTabSwitchWarning,
}));

describe('ExperimentalAiPage', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    vi.spyOn(window, 'scrollTo').mockImplementation(() => undefined);
    mockCreateSession.mockReset().mockResolvedValue('session-id');
    mockGetCapabilities.mockReset().mockResolvedValue({
      image_attachments: {
        enabled: false,
        accepted_media_types: ['image/jpeg', 'image/png', 'image/webp'],
        max_files: 4,
        max_bytes_per_file: 5_000_000,
      },
      document_attachments: {
        enabled: false,
        accepted_extensions: ['.txt', '.md', '.csv', '.pdf', '.xlsx'],
        max_files: 4,
        max_bytes_per_file: 5_000_000,
      },
    });
    mockStreamMessage.mockReset().mockImplementation(async (
      _sessionId: string,
      _message: string,
      callbacks: { onDelta: (text: string) => void },
    ) => {
      callbacks.onDelta('Alice');
      callbacks.onDelta(' works Monday.');
    });
    mockGenerateYaml.mockClear();
    mockApproveProposal.mockReset().mockResolvedValue('description: proposed schedule\n');
    mockRejectProposal.mockReset().mockResolvedValue(undefined);
    mockUpdateSessionSchedule.mockReset().mockResolvedValue(undefined);
    mockLoadFromYaml.mockReset();
    mockUseTabSwitchWarning.mockReset();
    window.localStorage.clear();
  });

  it('sends a question with the current schedule and renders streamed text', async () => {
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    expect(screen.getByText('Current snapshot: 0 people, 0 dates. Captured when you send the first question.')).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Experimental AI documentation' })).toHaveAttribute(
      'href',
      '/docs/user-guide/experimental-ai/',
    );
    expect(screen.getByRole('link', { name: 'Request beta access' })).toHaveAttribute(
      'href',
      'https://github.com/j3soon/nurse-scheduling#ai-beta-access',
    );
    expect(screen.getByRole('link', { name: 'Privacy details' })).toHaveAttribute(
      'href',
      'https://github.com/j3soon/nurse-scheduling/blob/dev/PRIVACY.md',
    );
    expect(screen.getByText(/Assume all AI chats are logged/)).toBeInTheDocument();
    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Who works Monday?');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    expect(await screen.findByText('Alice works Monday.')).toBeInTheDocument();
    expect(mockCreateSession).toHaveBeenCalledWith('description: current schedule\n', null, '/ai');
    expect(mockStreamMessage).toHaveBeenCalledWith(
      'session-id',
      'Who works Monday?',
      expect.any(Object),
      expect.any(AbortSignal),
      null,
      { images: [], documents: [] },
      '/ai',
    );
    expect(mockUseTabSwitchWarning).toHaveBeenLastCalledWith(true);
  });

  it('selects localhost and locks that server after the conversation starts', async () => {
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    await user.click(screen.getByRole('button', { name: 'Change' }));
    await user.click(screen.getByRole('button', { name: 'Use localhost' }));

    expect(screen.getByText('http://localhost:8001')).toBeInTheDocument();
    expect(window.localStorage.getItem('nurse-scheduling-ai-server')).toBe('http://localhost:8001');
    await waitFor(() => expect(mockGetCapabilities).toHaveBeenLastCalledWith(
      expect.any(AbortSignal),
      'http://localhost:8001',
    ));

    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Who works?');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    expect(mockCreateSession).toHaveBeenCalledWith(
      'description: current schedule\n',
      null,
      'http://localhost:8001',
    );
    expect(screen.getByRole('button', { name: 'Change' })).toBeDisabled();
    expect(screen.getByText('This server is locked for the current conversation.')).toBeInTheDocument();
  });

  it('normalizes a custom AI server URL', async () => {
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    await user.click(screen.getByRole('button', { name: 'Change' }));
    await user.type(screen.getByRole('textbox', { name: 'Custom AI server URL' }), 'ai.example.com/');
    await user.click(screen.getByRole('button', { name: 'Use custom' }));

    expect(screen.getByText('https://ai.example.com')).toBeInTheDocument();
    expect(window.localStorage.getItem('nurse-scheduling-ai-server')).toBe('https://ai.example.com');
  });

  it('ignores non-user scroll events while following streamed text', async () => {
    const user = userEvent.setup();
    let sendDelta: ((text: string) => void) | undefined;
    let finishStream: (() => void) | undefined;
    mockStreamMessage.mockImplementationOnce(async (
      _sessionId: string,
      _message: string,
      callbacks: { onDelta: (text: string) => void },
    ) => {
      sendDelta = callbacks.onDelta;
      await new Promise<void>(resolve => {
        finishStream = resolve;
      });
    });
    const scrollTo = vi.mocked(window.scrollTo);
    scrollTo.mockClear();
    let scrollYPosition = 100;
    const scrollHeight = vi.spyOn(document.documentElement, 'scrollHeight', 'get').mockReturnValue(900);
    const innerHeight = vi.spyOn(window, 'innerHeight', 'get').mockReturnValue(800);
    const scrollY = vi.spyOn(window, 'scrollY', 'get').mockImplementation(() => scrollYPosition);

    try {
      render(<ExperimentalAiPage />);
      await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Stream details.');
      await user.click(screen.getByRole('button', { name: 'Send' }));
      await waitFor(() => expect(sendDelta).toBeDefined());
      await waitFor(() => expect(scrollTo).toHaveBeenCalled());

      scrollYPosition = 99;
      act(() => {
        window.dispatchEvent(new Event('scroll'));
      });
      const callsBeforeDelta = scrollTo.mock.calls.length;
      act(() => sendDelta?.('More streamed content.'));

      await waitFor(() => expect(screen.getByText('More streamed content.')).toBeInTheDocument());
      expect(scrollTo.mock.calls.length).toBeGreaterThan(callsBeforeDelta);
      expect(screen.queryByRole('button', { name: 'Scroll to bottom' })).not.toBeInTheDocument();
      await act(async () => finishStream?.());
    } finally {
      scrollHeight.mockRestore();
      innerHeight.mockRestore();
      scrollY.mockRestore();
    }
  });

  it('stops following streamed text after a user scrolls above the bottom', async () => {
    const user = userEvent.setup();
    let sendDelta: ((text: string) => void) | undefined;
    let finishStream: (() => void) | undefined;
    mockStreamMessage.mockImplementationOnce(async (
      _sessionId: string,
      _message: string,
      callbacks: { onDelta: (text: string) => void },
    ) => {
      sendDelta = callbacks.onDelta;
      await new Promise<void>(resolve => {
        finishStream = resolve;
      });
    });
    const scrollTo = vi.mocked(window.scrollTo);
    const scrollHeight = vi.spyOn(document.documentElement, 'scrollHeight', 'get').mockReturnValue(900);
    const innerHeight = vi.spyOn(window, 'innerHeight', 'get').mockReturnValue(800);
    let scrollYPosition = 100;
    const scrollY = vi.spyOn(window, 'scrollY', 'get').mockImplementation(() => scrollYPosition);

    try {
      render(<ExperimentalAiPage />);
      await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Stream details.');
      await user.click(screen.getByRole('button', { name: 'Send' }));
      await waitFor(() => expect(sendDelta).toBeDefined());
      await waitFor(() => expect(scrollTo).toHaveBeenCalled());

      scrollYPosition = 99;
      act(() => {
        window.dispatchEvent(new WheelEvent('wheel', { deltaY: -1 }));
        window.dispatchEvent(new Event('scroll'));
      });
      await waitFor(() => expect(screen.getByRole('button', { name: 'Scroll to bottom' })).toBeInTheDocument());
      const callsBeforeDelta = scrollTo.mock.calls.length;
      act(() => sendDelta?.('More streamed content.'));

      await waitFor(() => expect(screen.getByText('More streamed content.')).toBeInTheDocument());
      expect(scrollTo).toHaveBeenCalledTimes(callsBeforeDelta);
      await act(async () => finishStream?.());
    } finally {
      scrollHeight.mockRestore();
      innerHeight.mockRestore();
      scrollY.mockRestore();
    }
  });

  it('resumes following streamed text when the user scrolls to the current bottom', async () => {
    const user = userEvent.setup();
    let sendDelta: ((text: string) => void) | undefined;
    let finishStream: (() => void) | undefined;
    mockStreamMessage.mockImplementationOnce(async (
      _sessionId: string,
      _message: string,
      callbacks: { onDelta: (text: string) => void },
    ) => {
      sendDelta = callbacks.onDelta;
      await new Promise<void>(resolve => {
        finishStream = resolve;
      });
    });
    let pageHeight = 900;
    let scrollYPosition = 100;
    const scrollTo = vi.mocked(window.scrollTo);
    const scrollHeight = vi.spyOn(document.documentElement, 'scrollHeight', 'get')
      .mockImplementation(() => pageHeight);
    const innerHeight = vi.spyOn(window, 'innerHeight', 'get').mockReturnValue(800);
    const scrollY = vi.spyOn(window, 'scrollY', 'get').mockImplementation(() => scrollYPosition);

    try {
      render(<ExperimentalAiPage />);
      await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Stream details.');
      await user.click(screen.getByRole('button', { name: 'Send' }));
      await waitFor(() => expect(sendDelta).toBeDefined());

      scrollYPosition = 99;
      act(() => {
        window.dispatchEvent(new WheelEvent('wheel', { deltaY: -1 }));
        window.dispatchEvent(new Event('scroll'));
      });
      await screen.findByRole('button', { name: 'Scroll to bottom' });

      scrollYPosition = 100;
      act(() => {
        window.dispatchEvent(new WheelEvent('wheel', { deltaY: 1 }));
        window.dispatchEvent(new Event('scroll'));
      });
      await waitFor(() => {
        expect(screen.queryByRole('button', { name: 'Scroll to bottom' })).not.toBeInTheDocument();
      });

      const callsBeforeGrowth = scrollTo.mock.calls.length;
      pageHeight = 901;
      act(() => sendDelta?.('More streamed content.'));
      await waitFor(() => expect(scrollTo.mock.calls.length).toBeGreaterThan(callsBeforeGrowth));
      await act(async () => finishStream?.());
    } finally {
      scrollHeight.mockRestore();
      innerHeight.mockRestore();
      scrollY.mockRestore();
    }
  });

  it('uses the same follow flag for streamed tool activity', async () => {
    const user = userEvent.setup();
    let startTool: ((activity: { name: string; arguments: string }) => void) | undefined;
    let finishTool: ((activity: { name: string; arguments: string; result: string; ok: boolean }) => void) | undefined;
    let finishStream: (() => void) | undefined;
    mockStreamMessage.mockImplementationOnce(async (
      _sessionId: string,
      _message: string,
      callbacks: {
        onToolStart?: (activity: { name: string; arguments: string }) => void;
        onTool?: (activity: { name: string; arguments: string; result: string; ok: boolean }) => void;
      },
    ) => {
      startTool = callbacks.onToolStart;
      finishTool = callbacks.onTool;
      await new Promise<void>(resolve => {
        finishStream = resolve;
      });
    });
    let scrollYPosition = 100;
    const scrollTo = vi.mocked(window.scrollTo);
    const scrollHeight = vi.spyOn(document.documentElement, 'scrollHeight', 'get').mockReturnValue(900);
    const innerHeight = vi.spyOn(window, 'innerHeight', 'get').mockReturnValue(800);
    const scrollY = vi.spyOn(window, 'scrollY', 'get').mockImplementation(() => scrollYPosition);
    const tool = { name: 'bash', arguments: '{"command":"date"}' };

    try {
      render(<ExperimentalAiPage />);
      await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Check the schedule.');
      await user.click(screen.getByRole('button', { name: 'Send' }));
      await waitFor(() => expect(startTool).toBeDefined());

      const callsBeforeTool = scrollTo.mock.calls.length;
      act(() => startTool?.(tool));
      await waitFor(() => expect(scrollTo.mock.calls.length).toBeGreaterThan(callsBeforeTool));

      scrollYPosition = 99;
      act(() => {
        window.dispatchEvent(new WheelEvent('wheel', { deltaY: -1 }));
        window.dispatchEvent(new Event('scroll'));
      });
      await screen.findByRole('button', { name: 'Scroll to bottom' });
      const callsBeforeResult = scrollTo.mock.calls.length;
      act(() => finishTool?.({ ...tool, result: 'exit_code: 0', ok: true }));

      await waitFor(() => expect(screen.getByText('bash')).toBeInTheDocument());
      expect(scrollTo).toHaveBeenCalledTimes(callsBeforeResult);
      await act(async () => finishStream?.());
    } finally {
      scrollHeight.mockRestore();
      innerHeight.mockRestore();
      scrollY.mockRestore();
    }
  });

  it('keeps alternating response and tool events in stream order', async () => {
    mockStreamMessage.mockImplementationOnce(async (
      _sessionId: string,
      _message: string,
      callbacks: {
        onDelta: (text: string) => void;
        onReasoning?: (text: string) => void;
        onToolStart?: (activity: { name: string; arguments: string }) => void;
        onTool?: (activity: { name: string; arguments: string; result: string; ok: boolean }) => void;
      },
    ) => {
      callbacks.onReasoning?.('First thought.');
      callbacks.onDelta('First response.');
      callbacks.onDelta(' Continued.');
      callbacks.onToolStart?.({ name: 'lookup', arguments: '{}' });
      callbacks.onTool?.({ name: 'lookup', arguments: '{}', result: 'found', ok: true });
      callbacks.onDelta('Second response.');
      callbacks.onToolStart?.({ name: 'calculate', arguments: '{}' });
      callbacks.onTool?.({ name: 'calculate', arguments: '{}', result: '42', ok: true });
      callbacks.onDelta('Final response.');
    });
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Work in stages.');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    const activity = await screen.findByLabelText('Assistant activity');
    const ordered = [
      screen.getByText('Reasoning · 14 characters'),
      screen.getByText('First response. Continued.'),
      screen.getByText('lookup'),
      screen.getByText('Second response.'),
      screen.getByText('calculate'),
      screen.getByText('Final response.'),
    ];
    ordered.slice(1).forEach((entry, index) => {
      expect(ordered[index].compareDocumentPosition(entry) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
    });
    expect(activity.querySelectorAll('hr')).toHaveLength(5);
  });

  it('allows drafting the next question while a response is streaming', async () => {
    const user = userEvent.setup();
    let finishStream: (() => void) | undefined;
    mockStreamMessage.mockImplementationOnce(async () => {
      await new Promise<void>(resolve => {
        finishStream = resolve;
      });
    });
    render(<ExperimentalAiPage />);
    const composer = screen.getByRole('textbox', { name: 'Ask about the current schedule' });

    await user.type(composer, 'First question.');
    await user.click(screen.getByRole('button', { name: 'Send' }));
    await screen.findByRole('button', { name: 'Stop' });

    expect(composer).toBeEnabled();
    await user.type(composer, 'Next question.');
    await user.keyboard('{Enter}');
    expect(mockStreamMessage).toHaveBeenCalledTimes(1);
    expect(composer).toHaveValue('Next question.');

    finishStream?.();
    await screen.findByRole('button', { name: 'Send' });
    expect(screen.getByRole('button', { name: 'Send' })).toBeEnabled();
  });

  it('requires the advertised AI token and uses a session-only credential', async () => {
    mockGetCapabilities.mockResolvedValueOnce({
      auth: { required: true, scheme: 'bearer' },
      image_attachments: {
        enabled: false,
        accepted_media_types: [],
        max_files: 1,
        max_bytes_per_file: 1,
      },
      document_attachments: {
        enabled: false,
        accepted_extensions: [],
        max_files: 1,
        max_bytes_per_file: 1,
      },
    });
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    const tokenButton = await screen.findByRole('button', { name: 'Enter token for AI assistant' });
    expect(screen.getByRole('textbox', { name: 'Ask about the current schedule' })).toBeDisabled();
    await user.click(tokenButton);
    await user.type(screen.getByLabelText('Token for AI assistant'), 'ai-session-token');
    await user.click(screen.getByRole('button', { name: 'Save token for AI assistant' }));

    expect(screen.getByText('Token set for this session')).toBeInTheDocument();
    expect(window.localStorage.getItem('nurse-scheduling-ai-auth')).toBeNull();
    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Who works?');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    await waitFor(() => expect(mockCreateSession).toHaveBeenCalledWith(
      'description: current schedule\n',
      'ai-session-token',
      '/ai',
    ));
    expect(mockStreamMessage.mock.calls[0][4]).toBe('ai-session-token');
  });

  it('remembers the AI token only when requested', async () => {
    mockGetCapabilities.mockResolvedValueOnce({
      auth: { required: true, scheme: 'bearer' },
      image_attachments: {
        enabled: false,
        accepted_media_types: [],
        max_files: 1,
        max_bytes_per_file: 1,
      },
      document_attachments: {
        enabled: false,
        accepted_extensions: [],
        max_files: 1,
        max_bytes_per_file: 1,
      },
    });
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    await user.click(await screen.findByRole('button', { name: 'Enter token for AI assistant' }));
    await user.type(screen.getByLabelText('Token for AI assistant'), 'remembered-ai-token');
    await user.click(screen.getByRole('checkbox', { name: /remember on this device/i }));
    await user.click(screen.getByRole('button', { name: 'Save token for AI assistant' }));

    expect(screen.getByText('Token saved on this device')).toBeInTheDocument();
    expect(JSON.parse(window.localStorage.getItem('nurse-scheduling-ai-auth') ?? '{}')).toEqual({
      tokens: { '/ai': 'remembered-ai-token' },
    });
  });

  it('restores a remembered token for the same AI endpoint', async () => {
    window.localStorage.setItem('nurse-scheduling-ai-auth', JSON.stringify({
      endpoint: '/ai',
      token: 'remembered-ai-token',
    }));
    mockGetCapabilities.mockResolvedValueOnce({
      auth: { required: true, scheme: 'bearer' },
      image_attachments: {
        enabled: false,
        accepted_media_types: [],
        max_files: 1,
        max_bytes_per_file: 1,
      },
      document_attachments: {
        enabled: false,
        accepted_extensions: [],
        max_files: 1,
        max_bytes_per_file: 1,
      },
    });
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    expect(await screen.findByText('Token saved on this device')).toBeInTheDocument();
    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Who works?');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    await waitFor(() => expect(mockCreateSession).toHaveBeenCalledWith(
      'description: current schedule\n',
      'remembered-ai-token',
      '/ai',
    ));
  });

  it('prompts for a replacement when the AI service rejects a token', async () => {
    mockGetCapabilities.mockResolvedValueOnce({
      auth: { required: true, scheme: 'bearer' },
      image_attachments: {
        enabled: false,
        accepted_media_types: [],
        max_files: 1,
        max_bytes_per_file: 1,
      },
      document_attachments: {
        enabled: false,
        accepted_extensions: [],
        max_files: 1,
        max_bytes_per_file: 1,
      },
    });
    mockCreateSession.mockRejectedValueOnce(Object.assign(new Error('Invalid credentials'), { status: 401 }));
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    await user.click(await screen.findByRole('button', { name: 'Enter token for AI assistant' }));
    await user.type(screen.getByLabelText('Token for AI assistant'), 'stale-ai-token');
    await user.click(screen.getByRole('button', { name: 'Save token for AI assistant' }));
    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Who works?');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    expect(await screen.findByRole('alert')).toHaveTextContent(
      'AI credentials were rejected. Enter the current AI token and try again.',
    );
    expect(screen.getByLabelText('Token for AI assistant')).toHaveValue('');
  });

  it('previews and sends images when the backend enables them', async () => {
    mockGetCapabilities.mockResolvedValueOnce({
      image_attachments: {
        enabled: true,
        accepted_media_types: ['image/png'],
        max_files: 2,
        max_bytes_per_file: 1000,
      },
      document_attachments: {
        enabled: false,
        accepted_extensions: ['.txt', '.md', '.csv', '.pdf', '.xlsx'],
        max_files: 4,
        max_bytes_per_file: 5_000_000,
      },
    });
    const createObjectUrl = vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:image-preview');
    const revokeObjectUrl = vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
    const user = userEvent.setup();
    const image = new File(['png'], 'ward.png', { type: 'image/png' });
    render(<ExperimentalAiPage />);

    const input = await screen.findByLabelText('Attach files');
    await user.upload(input, image);
    expect(screen.getByAltText('Preview of ward.png')).toBeInTheDocument();
    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'What is shown?');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    expect(mockStreamMessage).toHaveBeenCalledWith(
      'session-id',
      'What is shown?',
      expect.any(Object),
      expect.any(AbortSignal),
      null,
      { images: [image], documents: [] },
      '/ai',
    );
    expect(screen.getByText('Attached: ward.png')).toBeInTheDocument();
    expect(createObjectUrl).toHaveBeenCalledWith(image);
    expect(revokeObjectUrl).toHaveBeenCalledWith('blob:image-preview');
  });

  it('adds attachments dropped onto the message composer', async () => {
    mockGetCapabilities.mockResolvedValueOnce({
      image_attachments: {
        enabled: true,
        accepted_media_types: ['image/png'],
        max_files: 2,
        max_bytes_per_file: 1000,
      },
      document_attachments: {
        enabled: false,
        accepted_extensions: [],
        max_files: 1,
        max_bytes_per_file: 1,
      },
    });
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:dropped-image');
    const image = new File(['png'], 'dropped.png', { type: 'image/png' });
    render(<ExperimentalAiPage />);

    const composer = await screen.findByRole('form', { name: 'Message composer' });
    const dataTransfer = { files: [image], types: ['Files'], dropEffect: 'none' };
    fireEvent.dragEnter(composer, { dataTransfer });
    expect(screen.getByText('Drop files to attach')).toBeInTheDocument();

    fireEvent.dragOver(composer, { dataTransfer });
    expect(dataTransfer.dropEffect).toBe('copy');
    fireEvent.drop(composer, { dataTransfer });

    expect(screen.queryByText('Drop files to attach')).not.toBeInTheDocument();
    expect(screen.getByAltText('Preview of dropped.png')).toBeInTheDocument();
  });

  it('previews and sends text documents when the backend enables them', async () => {
    mockGetCapabilities.mockResolvedValueOnce({
      image_attachments: {
        enabled: false,
        accepted_media_types: ['image/png'],
        max_files: 2,
        max_bytes_per_file: 1000,
      },
      document_attachments: {
        enabled: true,
        accepted_extensions: ['.txt', '.md', '.csv', '.pdf', '.xlsx'],
        max_files: 2,
        max_bytes_per_file: 5_000_000,
      },
    });
    const user = userEvent.setup();
    const document = new File(['name,shift\nAlice,day\n'], 'staff.csv', { type: '' });
    render(<ExperimentalAiPage />);

    const input = await screen.findByLabelText('Attach files');
    await user.upload(input, document);
    expect(screen.getByText('csv')).toBeInTheDocument();
    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Check the CSV.');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    expect(mockStreamMessage).toHaveBeenCalledWith(
      'session-id',
      'Check the CSV.',
      expect.any(Object),
      expect.any(AbortSignal),
      null,
      {
        images: [],
        documents: [expect.objectContaining({ name: 'staff.csv', type: 'text/csv' })],
      },
      '/ai',
    );
    expect(screen.getByText('Attached: staff.csv')).toBeInTheDocument();
  });

  it('normalizes PDF and XLSX media types before upload', async () => {
    mockGetCapabilities.mockResolvedValueOnce({
      image_attachments: {
        enabled: false,
        accepted_media_types: [],
        max_files: 2,
        max_bytes_per_file: 1000,
      },
      document_attachments: {
        enabled: true,
        accepted_extensions: ['.pdf', '.xlsx'],
        max_files: 2,
        max_bytes_per_file: 5_000_000,
      },
    });
    const user = userEvent.setup();
    const pdf = new File(['pdf'], 'notes.pdf', { type: '' });
    const workbook = new File(['xlsx'], 'coverage.xlsx', { type: '' });
    render(<ExperimentalAiPage />);

    const input = await screen.findByLabelText('Attach files');
    await user.upload(input, [pdf, workbook]);
    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Read both files.');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    expect(mockStreamMessage).toHaveBeenCalledWith(
      'session-id',
      'Read both files.',
      expect.any(Object),
      expect.any(AbortSignal),
      null,
      {
        images: [],
        documents: [
          expect.objectContaining({ name: 'notes.pdf', type: 'application/pdf' }),
          expect.objectContaining({
            name: 'coverage.xlsx',
            type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          }),
        ],
      },
      '/ai',
    );
  });

  it('shows an error when capability discovery fails', async () => {
    mockGetCapabilities.mockRejectedValueOnce(new TypeError('Failed to fetch'));

    render(<ExperimentalAiPage />);

    expect(await screen.findByRole('alert')).toHaveTextContent(
      'Could not load AI capabilities from /ai. Check that the AI backend is reachable from this browser.',
    );
    expect(screen.queryByLabelText('Attach files')).not.toBeInTheDocument();
    expect(screen.getByRole('textbox', { name: 'Ask about the current schedule' })).toBeEnabled();
  });

  it('animates the thinking indicator while awaiting the first response token', async () => {
    let finishStream: (() => void) | undefined;
    mockStreamMessage.mockImplementationOnce(() => new Promise<void>(resolve => {
      finishStream = resolve;
    }));
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Think about this.');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    const thinking = await screen.findByRole('status', { name: 'Thinking' });
    expect(thinking.querySelectorAll('[style*="animation-delay"]')).toHaveLength(3);

    finishStream?.();
    await waitFor(() => expect(screen.queryByRole('status', { name: 'Thinking' })).not.toBeInTheDocument());
  });

  it('shows backend failures without discarding the user question', async () => {
    const providerError = 'The AI provider returned HTTP 525. Error ID: 72dc8f31-45af-410d-9fc2-41bdf1fc718f.';
    mockStreamMessage.mockImplementationOnce(async (
      _sessionId: string,
      _message: string,
      callbacks: { onDelta: (text: string) => void },
    ) => {
      callbacks.onDelta('Provisional response.');
      throw new Error(providerError);
    });
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Can you help?');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    const alert = await screen.findByRole('alert');
    expect(alert).toHaveTextContent(providerError);
    expect(screen.getByText('Can you help?')).toBeInTheDocument();
    expect(screen.getByText('Provisional response.')).toBeInTheDocument();
    expect(screen.getByText('This turn failed and was not saved to AI history.')).toBeInTheDocument();

    await user.click(screen.getByRole('button', { name: 'Retry' }));

    expect(await screen.findByText('Alice works Monday.')).toBeInTheDocument();
    expect(mockStreamMessage).toHaveBeenCalledTimes(2);
    expect(mockStreamMessage.mock.calls[1][1]).toBe('Can you help?');
    expect(screen.getAllByText('Can you help?')).toHaveLength(1);
    expect(screen.queryByText('Provisional response.')).not.toBeInTheDocument();
    expect(screen.queryByText('This turn failed and was not saved to AI history.')).not.toBeInTheDocument();
  });

  it('removes provisional output when the backend discards a stale turn', async () => {
    mockStreamMessage.mockImplementationOnce(async (
      _sessionId: string,
      _message: string,
      callbacks: {
        onDelta: (text: string) => void;
        onScheduleChange?: (scheduleYaml: string) => void;
      },
    ) => {
      callbacks.onScheduleChange?.('description: obsolete proposal');
      callbacks.onDelta('Obsolete response.');
      throw new MockAiStaleTurnError('The schedule changed.');
    });
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Change it.');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    expect(await screen.findByText('This turn failed and was not saved to AI history.')).toBeInTheDocument();
    expect(screen.getByText('The schedule changed.')).toBeInTheDocument();
    expect(screen.queryByText('Obsolete response.')).not.toBeInTheDocument();
    expect(screen.queryByText('schedule edit')).not.toBeInTheDocument();
    expect(screen.queryByRole('alert')).not.toBeInTheDocument();
  });

  it('requires files to be reattached before retrying an attachment request', async () => {
    mockGetCapabilities.mockResolvedValueOnce({
      image_attachments: {
        enabled: true,
        accepted_media_types: ['image/png'],
        max_files: 2,
        max_bytes_per_file: 1000,
      },
      document_attachments: {
        enabled: false,
        accepted_extensions: [],
        max_files: 1,
        max_bytes_per_file: 1,
      },
    });
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:image-preview');
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
    mockStreamMessage.mockRejectedValueOnce(new Error('The temporary AI sandbox failed.'));
    const user = userEvent.setup();
    const image = new File(['png'], 'ward.png', { type: 'image/png' });
    render(<ExperimentalAiPage />);

    await user.upload(await screen.findByLabelText('Attach files'), image);
    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Check this image.');
    await user.click(screen.getByRole('button', { name: 'Send' }));
    await user.click(await screen.findByRole('button', { name: 'Prepare retry' }));

    expect(screen.getByRole('textbox', { name: 'Ask about the current schedule' })).toHaveValue('Check this image.');
    expect(screen.getByText('Prepare the question, then reattach its files before sending.')).toBeInTheDocument();
    expect(mockStreamMessage).toHaveBeenCalledTimes(1);
  });

  describe('proposals', () => {
    const proposingStream = (
      _sessionId: string,
      _message: string,
      callbacks: {
        onDelta: (text: string) => void;
        onReasoning?: (text: string) => void;
        onToolStart?: (activity: { name: string; arguments: string }) => void;
        onTool?: (activity: { name: string; arguments: string; result: string; ok: boolean }) => void;
        onScheduleChange?: (scheduleYaml: string) => void;
        onProposal?: (diff: string) => void;
      },
    ) => {
      callbacks.onReasoning?.('Looking at P1. ');
      callbacks.onToolStart?.({
        name: 'bash',
        arguments: JSON.stringify({ command: "sed -i 's/old/new/' schedule.yaml" }),
      });
      callbacks.onTool?.({
        name: 'bash',
        arguments: JSON.stringify({ command: "sed -i 's/old/new/' schedule.yaml" }),
        result: 'exit_code: 0',
        ok: true,
      });
      callbacks.onScheduleChange?.('description: Head');
      callbacks.onDelta('I propose renaming P1.');
      callbacks.onProposal?.('- people.items[0].description: "" -> "Head"');
    };

    const ask = async (user: ReturnType<typeof userEvent.setup>) => {
      await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Rename P1.');
      await user.click(screen.getByRole('button', { name: 'Send' }));
    };

    beforeEach(() => {
      mockStreamMessage.mockReset().mockImplementation(proposingStream);
    });

    it('shows the proposed change and what the assistant did', async () => {
      const user = userEvent.setup();
      render(<ExperimentalAiPage />);

      await ask(user);

      expect(await screen.findByRole('region', { name: 'Proposed schedule change' })).toBeInTheDocument();
      expect(screen.getByText('- people.items[0].description: "" -> "Head"')).toBeInTheDocument();
      expect(screen.getByText('bash')).toBeInTheDocument();
      expect(screen.getByText('schedule edit')).toBeInTheDocument();
      expect(screen.getByText(/^Reasoning ·/)).toBeInTheDocument();
      const activity = screen.getByLabelText('Assistant activity');
      const response = screen.getByText('I propose renaming P1.');
      expect(activity.compareDocumentPosition(response) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
    });

    it('applies an approved proposal as one history entry', async () => {
      const user = userEvent.setup();
      render(<ExperimentalAiPage />);
      await ask(user);

      await user.click(await screen.findByRole('button', { name: 'Approve' }));

      await waitFor(() => expect(mockLoadFromYaml).toHaveBeenCalledTimes(1));
      expect(mockApproveProposal).toHaveBeenCalledWith('session-id', 'description: current schedule\n', null, '/ai');
      expect(mockLoadFromYaml).toHaveBeenCalledWith({ description: 'proposed schedule' });
      expect(screen.queryByRole('region', { name: 'Proposed schedule change' })).not.toBeInTheDocument();
      expect(screen.getByText('The proposed schedule was applied. Undo reverts it in one step.')).toBeInTheDocument();
    });

    it('reports a proposal that no longer matches the current schedule', async () => {
      mockApproveProposal.mockRejectedValue(new Error('The schedule changed after this proposal was created.'));
      const user = userEvent.setup();
      render(<ExperimentalAiPage />);
      await ask(user);

      await user.click(await screen.findByRole('button', { name: 'Approve' }));

      expect(await screen.findByText('The schedule changed after this proposal was created.')).toBeInTheDocument();
      expect(mockLoadFromYaml).not.toHaveBeenCalled();
    });

    it('drops a rejected proposal', async () => {
      const user = userEvent.setup();
      render(<ExperimentalAiPage />);
      await ask(user);

      await user.click(await screen.findByRole('button', { name: 'Reject' }));

      await waitFor(() => expect(mockRejectProposal).toHaveBeenCalledWith('session-id', null, '/ai'));
      expect(screen.queryByRole('region', { name: 'Proposed schedule change' })).not.toBeInTheDocument();
      expect(mockLoadFromYaml).not.toHaveBeenCalled();
    });

    it('sends a changed schedule to an existing session before the next question', async () => {
      const user = userEvent.setup();
      render(<ExperimentalAiPage />);
      await ask(user);
      mockGenerateYaml.mockReturnValue('description: edited elsewhere\n');

      await ask(user);

      await waitFor(() => expect(mockUpdateSessionSchedule).toHaveBeenCalledWith(
        'session-id',
        'description: edited elsewhere\n',
        null,
        '/ai',
      ));
      expect(mockCreateSession).toHaveBeenCalledTimes(1);
    });
  });
});
