/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import ExperimentalAiPage from './page';

const mockCreateSession = vi.hoisted(() => vi.fn());
const mockGetCapabilities = vi.hoisted(() => vi.fn());
const mockStreamMessage = vi.hoisted(() => vi.fn());
const mockGenerateYaml = vi.hoisted(() => vi.fn(() => 'description: current schedule\n'));

vi.mock('./aiClient', () => ({
  createSession: mockCreateSession,
  getCapabilities: mockGetCapabilities,
  streamMessage: mockStreamMessage,
}));

vi.mock('@/utils/yamlGenerator', () => ({
  generateYamlFromState: mockGenerateYaml,
}));

vi.mock('@/hooks/useSchedulingData', () => ({
  useSchedulingData: () => ({
    apiVersionData: 'alpha',
    descriptionData: 'current schedule',
    dateData: { items: [], groups: [], range: {} },
    peopleData: { items: [], groups: [] },
    shiftTypeData: { items: [], groups: [] },
    preferences: [],
    exportData: undefined,
    filterAutoGeneratedState: (state: unknown) => state,
  }),
}));

describe('ExperimentalAiPage', () => {
  beforeEach(() => {
    mockCreateSession.mockReset().mockResolvedValue('session-id');
    mockGetCapabilities.mockReset().mockResolvedValue({
      image_attachments: {
        enabled: false,
        accepted_media_types: ['image/jpeg', 'image/png', 'image/webp'],
        max_files: 4,
        max_bytes_per_file: 5_000_000,
      },
      document_attachments: {
        enabled: false,
        accepted_extensions: ['.txt', '.md', '.csv'],
        max_files: 4,
        max_bytes_per_file: 50_000,
      },
    });
    mockStreamMessage.mockReset().mockImplementation(async (
      _sessionId: string,
      _message: string,
      callbacks: { onDelta: (text: string) => void },
    ) => {
      callbacks.onDelta('Alice');
      callbacks.onDelta(' works Monday.');
    });
    mockGenerateYaml.mockClear();
  });

  it('sends a question with the current schedule and renders streamed text', async () => {
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    expect(screen.getByText('Current snapshot: 0 people, 0 dates. Captured when you send the first question.')).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Experimental AI documentation' })).toHaveAttribute(
      'href',
      '/docs/user-guide/experimental-ai/',
    );
    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Who works Monday?');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    expect(await screen.findByText('Alice works Monday.')).toBeInTheDocument();
    expect(mockCreateSession).toHaveBeenCalledWith('description: current schedule\n');
    expect(mockStreamMessage).toHaveBeenCalledWith(
      'session-id',
      'Who works Monday?',
      expect.any(Object),
      expect.any(AbortSignal),
      { images: [], documents: [] },
    );
  });

  it('previews and sends images when the backend enables them', async () => {
    mockGetCapabilities.mockResolvedValueOnce({
      image_attachments: {
        enabled: true,
        accepted_media_types: ['image/png'],
        max_files: 2,
        max_bytes_per_file: 1000,
      },
      document_attachments: {
        enabled: false,
        accepted_extensions: ['.txt', '.md', '.csv'],
        max_files: 4,
        max_bytes_per_file: 50_000,
      },
    });
    const createObjectUrl = vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:image-preview');
    const revokeObjectUrl = vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
    const user = userEvent.setup();
    const image = new File(['png'], 'ward.png', { type: 'image/png' });
    render(<ExperimentalAiPage />);

    const input = await screen.findByLabelText('Attach files');
    await user.upload(input, image);
    expect(screen.getByAltText('Preview of ward.png')).toBeInTheDocument();
    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'What is shown?');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    expect(mockStreamMessage).toHaveBeenCalledWith(
      'session-id',
      'What is shown?',
      expect.any(Object),
      expect.any(AbortSignal),
      { images: [image], documents: [] },
    );
    expect(screen.getByText('Attached: ward.png')).toBeInTheDocument();
    expect(createObjectUrl).toHaveBeenCalledWith(image);
    expect(revokeObjectUrl).toHaveBeenCalledWith('blob:image-preview');
  });

  it('previews and sends text documents when the backend enables them', async () => {
    mockGetCapabilities.mockResolvedValueOnce({
      image_attachments: {
        enabled: false,
        accepted_media_types: ['image/png'],
        max_files: 2,
        max_bytes_per_file: 1000,
      },
      document_attachments: {
        enabled: true,
        accepted_extensions: ['.txt', '.md', '.csv'],
        max_files: 2,
        max_bytes_per_file: 50_000,
      },
    });
    const user = userEvent.setup();
    const document = new File(['name,shift\nAlice,day\n'], 'staff.csv', { type: '' });
    render(<ExperimentalAiPage />);

    const input = await screen.findByLabelText('Attach files');
    await user.upload(input, document);
    expect(screen.getByText('csv')).toBeInTheDocument();
    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Check the CSV.');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    expect(mockStreamMessage).toHaveBeenCalledWith(
      'session-id',
      'Check the CSV.',
      expect.any(Object),
      expect.any(AbortSignal),
      {
        images: [],
        documents: [expect.objectContaining({ name: 'staff.csv', type: 'text/csv' })],
      },
    );
    expect(screen.getByText('Attached: staff.csv')).toBeInTheDocument();
  });

  it('shows an error when capability discovery fails', async () => {
    mockGetCapabilities.mockRejectedValueOnce(new TypeError('Failed to fetch'));

    render(<ExperimentalAiPage />);

    expect(await screen.findByRole('alert')).toHaveTextContent(
      'Could not load AI capabilities. Check that the AI backend is reachable from this browser, then reload the page.',
    );
    expect(screen.queryByLabelText('Attach files')).not.toBeInTheDocument();
    expect(screen.getByRole('textbox', { name: 'Ask about the current schedule' })).toBeEnabled();
  });

  it('shows backend failures without discarding the user question', async () => {
    mockStreamMessage.mockRejectedValueOnce(new Error('Provider unavailable.'));
    const user = userEvent.setup();
    render(<ExperimentalAiPage />);

    await user.type(screen.getByRole('textbox', { name: 'Ask about the current schedule' }), 'Can you help?');
    await user.click(screen.getByRole('button', { name: 'Send' }));

    expect(await screen.findByRole('alert')).toHaveTextContent('Provider unavailable.');
    expect(screen.getByText('Can you help?')).toBeInTheDocument();
  });
});
