/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

'use client';

import Image from 'next/image';
import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import PageDocumentationLink from '@/components/PageDocumentationLink';
import { DOCUMENTATION_URLS } from '@/constants/urls';
import { useSchedulingData } from '@/hooks/useSchedulingData';
import { generateYamlFromState } from '@/utils/yamlGenerator';
import AssistantMarkdown from './AssistantMarkdown';
import { AiCapabilities, createSession, getCapabilities, streamMessage } from './aiClient';

interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  attachmentNames?: string[];
}

interface SelectedAttachment {
  id: string;
  file: File;
  kind: 'image' | 'document';
  previewUrl?: string;
}

const DISABLED_IMAGE_CAPABILITY: AiCapabilities['image_attachments'] = {
  enabled: false,
  accepted_media_types: [],
  max_files: 1,
  max_bytes_per_file: 1,
};

const DISABLED_DOCUMENT_CAPABILITY: AiCapabilities['document_attachments'] = {
  enabled: false,
  accepted_extensions: [],
  max_files: 1,
  max_bytes_per_file: 1,
};

const DOCUMENT_MEDIA_TYPES: Record<string, string> = {
  '.txt': 'text/plain',
  '.md': 'text/markdown',
  '.csv': 'text/csv',
};

function fileExtension(filename: string): string {
  const lastDot = filename.lastIndexOf('.');
  return lastDot < 0 ? '' : filename.slice(lastDot).toLowerCase();
}

function messageId(): string {
  return typeof crypto.randomUUID === 'function'
    ? crypto.randomUUID()
    : `${Date.now()}-${Math.random()}`;
}

export default function ExperimentalAiPage() {
  const {
    apiVersionData,
    descriptionData,
    dateData,
    peopleData,
    shiftTypeData,
    preferences,
    exportData,
    filterAutoGeneratedState,
  } = useSchedulingData();
  const scheduleYaml = useMemo(() => generateYamlFromState(filterAutoGeneratedState({
    apiVersion: apiVersionData,
    description: descriptionData,
    dates: dateData,
    people: peopleData,
    shiftTypes: shiftTypeData,
    preferences,
    ...(exportData ? { export: exportData } : {}),
  })), [
    apiVersionData,
    dateData,
    descriptionData,
    exportData,
    filterAutoGeneratedState,
    peopleData,
    preferences,
    shiftTypeData,
  ]);

  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [draft, setDraft] = useState('');
  const [isStreaming, setIsStreaming] = useState(false);
  const [isClientReady, setIsClientReady] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [capabilitiesError, setCapabilitiesError] = useState<string | null>(null);
  const [imageCapability, setImageCapability] = useState(DISABLED_IMAGE_CAPABILITY);
  const [documentCapability, setDocumentCapability] = useState(DISABLED_DOCUMENT_CAPABILITY);
  const [selectedAttachments, setSelectedAttachments] = useState<SelectedAttachment[]>([]);
  const sessionIdRef = useRef<string | null>(null);
  const abortControllerRef = useRef<AbortController | null>(null);
  const selectedAttachmentsRef = useRef<SelectedAttachment[]>([]);

  useEffect(() => {
    const capabilitiesController = new AbortController();
    setIsClientReady(true);
    getCapabilities(capabilitiesController.signal)
      .then(capabilities => {
        setImageCapability(capabilities.image_attachments);
        setDocumentCapability(capabilities.document_attachments);
      })
      .catch(() => {
        if (!capabilitiesController.signal.aborted) {
          setCapabilitiesError(
            'Could not load AI capabilities. Check that the AI backend is reachable from this browser, then reload the page.',
          );
        }
      });
    return () => {
      capabilitiesController.abort();
      abortControllerRef.current?.abort();
      selectedAttachmentsRef.current.forEach(attachment => {
        if (attachment.previewUrl) URL.revokeObjectURL(attachment.previewUrl);
      });
    };
  }, []);

  useEffect(() => {
    selectedAttachmentsRef.current = selectedAttachments;
  }, [selectedAttachments]);

  const selectAttachments = (event: ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files ?? []);
    event.target.value = '';
    if (files.length === 0) return;

    const candidates = files.map(file => {
      if (imageCapability.enabled && imageCapability.accepted_media_types.includes(file.type)) {
        return { file, kind: 'image' as const };
      }
      const extension = fileExtension(file.name);
      if (documentCapability.enabled && documentCapability.accepted_extensions.includes(extension)) {
        const normalizedFile = new File([file], file.name, {
          type: DOCUMENT_MEDIA_TYPES[extension] ?? 'text/plain',
          lastModified: file.lastModified,
        });
        return { file: normalizedFile, kind: 'document' as const };
      }
      return null;
    });
    if (candidates.some(candidate => candidate === null)) {
      setError('Attach only a supported image, TXT, Markdown, or CSV file.');
      return;
    }
    const attachments = candidates.filter(candidate => candidate !== null);
    const selectedImageCount = selectedAttachments.filter(attachment => attachment.kind === 'image').length;
    const selectedDocumentCount = selectedAttachments.length - selectedImageCount;
    const imageCount = attachments.filter(attachment => attachment.kind === 'image').length;
    const documentCount = attachments.length - imageCount;
    if (selectedImageCount + imageCount > imageCapability.max_files) {
      setError(`Attach at most ${imageCapability.max_files} images to one question.`);
      return;
    }
    if (selectedDocumentCount + documentCount > documentCapability.max_files) {
      setError(`Attach at most ${documentCapability.max_files} documents to one question.`);
      return;
    }
    if (attachments.some(attachment => (
      attachment.kind === 'image' && attachment.file.size > imageCapability.max_bytes_per_file
    ))) {
      const maxMegabytes = (imageCapability.max_bytes_per_file / 1_000_000).toLocaleString(undefined, {
        maximumFractionDigits: 1,
      });
      setError(`Each image must be ${maxMegabytes} MB or smaller.`);
      return;
    }
    if (attachments.some(attachment => (
      attachment.kind === 'document' && attachment.file.size > documentCapability.max_bytes_per_file
    ))) {
      const maxKilobytes = Math.floor(documentCapability.max_bytes_per_file / 1000).toLocaleString();
      setError(`Each document must be ${maxKilobytes} KB or smaller.`);
      return;
    }

    setError(null);
    setSelectedAttachments(previous => [
      ...previous,
      ...attachments.map(attachment => ({
        ...attachment,
        id: messageId(),
        ...(attachment.kind === 'image' ? { previewUrl: URL.createObjectURL(attachment.file) } : {}),
      })),
    ]);
  };

  const removeAttachment = (id: string) => {
    setSelectedAttachments(previous => {
      const removed = previous.find(attachment => attachment.id === id);
      if (removed?.previewUrl) URL.revokeObjectURL(removed.previewUrl);
      return previous.filter(attachment => attachment.id !== id);
    });
  };

  const send = async (event: FormEvent) => {
    event.preventDefault();
    const question = draft.trim();
    if (!question || isStreaming) return;

    const attachmentsForMessage = selectedAttachments;
    const userMessage: ChatMessage = {
      id: messageId(),
      role: 'user',
      content: question,
      attachmentNames: attachmentsForMessage.map(attachment => attachment.file.name),
    };
    const assistantId = messageId();
    setMessages(previous => [...previous, userMessage, { id: assistantId, role: 'assistant', content: '' }]);
    setDraft('');
    attachmentsForMessage.forEach(attachment => {
      if (attachment.previewUrl) URL.revokeObjectURL(attachment.previewUrl);
    });
    setSelectedAttachments([]);
    setError(null);
    setIsStreaming(true);
    const controller = new AbortController();
    abortControllerRef.current = controller;

    try {
      const sessionId = sessionIdRef.current ?? await createSession(scheduleYaml);
      sessionIdRef.current = sessionId;
      await streamMessage(
        sessionId,
        question,
        {
          onDelta: text => setMessages(previous => previous.map(message => (
            message.id === assistantId ? { ...message, content: message.content + text } : message
          ))),
        },
        controller.signal,
        {
          images: attachmentsForMessage
            .filter(attachment => attachment.kind === 'image')
            .map(attachment => attachment.file),
          documents: attachmentsForMessage
            .filter(attachment => attachment.kind === 'document')
            .map(attachment => attachment.file),
        },
      );
    } catch (streamError) {
      if (!controller.signal.aborted) {
        setError(streamError instanceof Error ? streamError.message : 'The AI request failed.');
      }
    } finally {
      abortControllerRef.current = null;
      setIsStreaming(false);
    }
  };

  const stop = () => abortControllerRef.current?.abort();
  const selectedImageCount = selectedAttachments.filter(attachment => attachment.kind === 'image').length;
  const selectedDocumentCount = selectedAttachments.length - selectedImageCount;
  const attachmentPickerDisabled = isStreaming || (
    (!imageCapability.enabled || selectedImageCount >= imageCapability.max_files)
    && (!documentCapability.enabled || selectedDocumentCount >= documentCapability.max_files)
  );

  return (
    <main className="mx-auto flex min-h-[calc(100vh-8rem)] max-w-5xl flex-col px-4 py-8 sm:px-6">
      <div className="mb-6">
        <div className="mb-2 flex items-center gap-3">
          <h1 className="text-3xl font-bold text-gray-900">Schedule AI Chat</h1>
          <PageDocumentationLink href={DOCUMENTATION_URLS.experimentalAi} label="Experimental AI" />
          <span className="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-semibold text-amber-800">
            Experimental
          </span>
        </div>
        <p className="text-sm text-gray-600">
          Ask questions about the schedule currently open in this browser. You can attach supported images and text documents when the backend enables them, but the assistant cannot change the schedule.
        </p>
        <p className="mt-2 text-xs font-medium text-gray-500">
          Current snapshot: {peopleData.items.length} people, {dateData.items.length} dates. Captured when you send the first question.
        </p>
      </div>

      <section
        aria-label="Chat messages"
        aria-live="polite"
        className="mb-4 min-h-80 flex-1 space-y-4 overflow-y-auto rounded-xl border border-gray-200 bg-gray-50 p-4"
      >
        {messages.length === 0 && (
          <div className="flex min-h-72 items-center justify-center text-center text-gray-500">
            <p>Try asking “Who is available on the first date?”</p>
          </div>
        )}
        {messages.map(message => (
          <article
            key={message.id}
            className={`max-w-[85%] rounded-xl px-4 py-3 ${
              message.role === 'user'
                ? 'ml-auto bg-blue-600 text-white'
                : 'mr-auto border border-gray-200 bg-white text-gray-900'
            }`}
          >
            <p className="mb-1 text-xs font-semibold uppercase tracking-wide opacity-70">
              {message.role === 'user' ? 'You' : 'Assistant'}
            </p>
            {message.role === 'assistant' && message.content ? (
              <AssistantMarkdown content={message.content} />
            ) : (
              <p className="whitespace-pre-wrap break-words">
                {message.content || (isStreaming ? 'Thinking…' : '')}
              </p>
            )}
            {message.attachmentNames && message.attachmentNames.length > 0 && (
              <p className="mt-2 text-xs opacity-80">
                Attached: {message.attachmentNames.join(', ')}
              </p>
            )}
          </article>
        ))}
      </section>

      {error && (
        <div role="alert" className="mb-3 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          {error}
        </div>
      )}

      {capabilitiesError && (
        <div role="alert" className="mb-3 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
          {capabilitiesError}
        </div>
      )}

      <form onSubmit={send} className="space-y-3">
        {selectedAttachments.length > 0 && (
          <div aria-label="Files attached to next message" className="flex flex-wrap gap-3 rounded-xl border border-gray-200 bg-white p-3">
            {selectedAttachments.map(attachment => (
              <div key={attachment.id} className="flex max-w-52 items-center gap-2 rounded-lg bg-gray-50 p-2">
                {attachment.previewUrl ? (
                  <Image
                    src={attachment.previewUrl}
                    alt={`Preview of ${attachment.file.name}`}
                    width={48}
                    height={48}
                    unoptimized
                    className="h-12 w-12 rounded-md object-cover"
                  />
                ) : (
                  <span className="flex h-12 w-12 items-center justify-center rounded-md bg-blue-50 text-xs font-semibold uppercase text-blue-700">
                    {fileExtension(attachment.file.name).slice(1)}
                  </span>
                )}
                <span className="min-w-0 flex-1 truncate text-xs text-gray-700">{attachment.file.name}</span>
                <button
                  type="button"
                  onClick={() => removeAttachment(attachment.id)}
                  aria-label={`Remove ${attachment.file.name}`}
                  className="rounded px-1.5 py-1 text-gray-500 hover:bg-gray-200 hover:text-gray-800"
                >
                  ×
                </button>
              </div>
            ))}
          </div>
        )}
        <div className="flex flex-col gap-3 sm:flex-row sm:items-end">
          {(imageCapability.enabled || documentCapability.enabled) && (
            <label className={`order-2 rounded-xl border px-3 py-3 text-center text-sm font-medium sm:order-1 ${
              attachmentPickerDisabled
                ? 'cursor-not-allowed border-gray-200 bg-gray-100 text-gray-400'
                : 'cursor-pointer border-gray-300 bg-white text-gray-700 hover:bg-gray-50'
            }`}>
              <input
                type="file"
                accept={[
                  ...(imageCapability.enabled ? imageCapability.accepted_media_types : []),
                  ...(documentCapability.enabled ? documentCapability.accepted_extensions : []),
                ].join(',')}
                multiple
                disabled={attachmentPickerDisabled}
                onChange={selectAttachments}
                className="sr-only"
              />
              Attach files
            </label>
          )}
          <label className="order-1 flex-1 sm:order-2">
            <span className="sr-only">Ask about the current schedule</span>
            <textarea
              value={draft}
              onChange={event => setDraft(event.target.value)}
              onKeyDown={event => {
                if (event.key === 'Enter' && !event.shiftKey) {
                  event.preventDefault();
                  event.currentTarget.form?.requestSubmit();
                }
              }}
              disabled={!isClientReady || isStreaming}
              rows={3}
              maxLength={8000}
              placeholder="Ask about the current schedule…"
              className="w-full resize-none rounded-xl border border-gray-300 bg-white px-4 py-3 text-gray-900 shadow-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-200 disabled:bg-gray-100"
            />
          </label>
          {isStreaming ? (
            <button
              type="button"
              onClick={stop}
              className="order-3 rounded-xl bg-gray-800 px-5 py-3 font-medium text-white hover:bg-gray-900"
            >
              Stop
            </button>
          ) : (
            <button
              type="submit"
              disabled={!isClientReady || !draft.trim()}
              className="order-3 rounded-xl bg-blue-600 px-5 py-3 font-medium text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:bg-gray-300"
            >
              Send
            </button>
          )}
        </div>
      </form>
    </main>
  );
}
