import { DataType, AutoGeneratedGroup, Item, Group, DateRange } from '@/types/scheduling';
import { dateStrToDate } from './dateParsing';

export const AUTO_GENERATED_GROUPS: Record<DataType, AutoGeneratedGroup[]> = {
  [DataType.PEOPLE]: [
    {
      id: 'All',
      description: 'Group containing all people',
      generateMembers: (items: Item[]) => items.map(item => item.id)
    }
  ],
  [DataType.SHIFT_TYPES]: [
    {
      id: 'All',
      description: 'Group containing all shift types',
      generateMembers: (items: Item[]) => items.map(item => item.id)
    }
  ],
  [DataType.DATES]: [
    {
      id: 'All',
      description: 'Group containing all dates',
      generateMembers: (items: Item[]) => items.map(item => item.id)
    },
    {
      id: 'Weekday',
      description: 'Group containing all weekdays',
      generateMembers: (items: Item[], dateRange?: DateRange) => {
        return dateRange && dateRange.startDate ? items.filter(item => {
            const dayOfWeek = dateStrToDate(item.id, dateRange!).getDay();
            // 0 = Sunday, 6 = Saturday
            return dayOfWeek >= 1 && dayOfWeek <= 5;
          }).map(item => item.id) : [];
      }
    },
    {
      id: 'Weekend',
      description: 'Group containing all weekends',
      generateMembers: (items: Item[], dateRange?: DateRange) => {
        return dateRange && dateRange.startDate ? items.filter(item => {
            const dayOfWeek = dateStrToDate(item.id, dateRange!).getDay();
            // 0 = Sunday, 6 = Saturday
            return dayOfWeek === 0 || dayOfWeek === 6;
          }).map(item => item.id) : [];
        }
    }
  ]
};

export function getReservedKeywords(dataType: DataType): string[] {
  return AUTO_GENERATED_GROUPS[dataType].map(group => group.id);
}

export function isReservedKeyword(dataType: DataType, id: string): boolean {
  return getReservedKeywords(dataType).some(keyword => keyword.toLowerCase() === id.toLowerCase());
}

export function filterAutoGenerated(items: (Item | Group)[]): (Item | Group)[] {
  return items.filter(item => !item.isAutoGenerated);
}
