/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// The Optimize and Export page for Tab "11. Optimize and Export"
'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { FiHelpCircle, FiDownload, FiAlertCircle, FiCheckCircle, FiLoader } from 'react-icons/fi';
import { useSchedulingData } from '@/hooks/useSchedulingData';
import { formatProgressMessage, type ProgressEvent } from '@/utils/progressMessages';
import { generateYamlFromState } from '@/utils/yamlGenerator';

export default function OptimizeAndExportPage() {
  const {
    apiVersionData,
    descriptionData,
    dateData,
    peopleData,
    shiftTypeData,
    preferences,
    effectiveExportData,
    filterAutoGeneratedState
  } = useSchedulingData();

  const [showInstructions, setShowInstructions] = useState(false);
  const [apiEndpoint, setApiEndpoint] = useState(process.env.NEXT_PUBLIC_BACKEND_API_URL || 'http://localhost:8000');
  const [prettifyArg, setPrettifyArg] = useState(true);
  const [timeoutArg, setTimeoutArg] = useState<number>(300);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [scheduleFilename, setScheduleFilename] = useState<string | null>(null);
  const [scheduleScore, setScheduleScore] = useState<string | null>(null);
  const [scheduleStatus, setScheduleStatus] = useState<string | null>(null);
  const isDateDataMissing = !dateData.range?.startDate || !dateData.range?.endDate || dateData.items.length === 0;
  const isPeopleDataMissing = peopleData.items.length === 0;
  const isShiftTypeDataMissing = shiftTypeData.items.length === 0 && shiftTypeData.groups.length === 0;
  const isRequiredDataMissing = isDateDataMissing || isPeopleDataMissing || isShiftTypeDataMissing;
  const [progressLogs, setProgressLogs] = useState<string[]>([]);
  const [progressValue, setProgressValue] = useState<number | null>(null);
  const [isTaskFinished, setIsTaskFinished] = useState(false);
  const eventSourceRef = useRef<EventSource | null>(null);

  const instructions = [
    "This page sends your current scheduling configuration to the optimization server",
    "The server will compute an optimal schedule and return an Excel (.xlsx) file",
    "Configure optimization options (prettify and timeout) before submitting",
    "Prettify: Enables prettier output formatting in the generated schedule",
    "Timeout: Maximum time (in seconds) the optimizer will run before stopping",
    "Click 'Optimize and Download' to generate your schedule",
    "The optimization score and status will be displayed after completion",
    "Real-time progress logs are shown during optimization"
  ];

  // Create the current state object for YAML export (filtering out autogenerated items)
  const filteredState = filterAutoGeneratedState({
    apiVersion: apiVersionData,
    description: descriptionData,
    dates: dateData,
    people: peopleData,
    shiftTypes: shiftTypeData,
    preferences,
    export: effectiveExportData
  });

  // Convert current state to YAML
  const currentYaml = generateYamlFromState(filteredState);

  useEffect(() => {
    return () => {
      eventSourceRef.current?.close();
    };
  }, []);

  const appendProgressLog = (line: string) => {
    setProgressLogs((logs) => [...logs, line].slice(-100));
  };

  const downloadJobResult = async (jobId: string) => {
    const response = await fetch(`${apiEndpoint}/optimization-jobs/${jobId}/result`);

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Download failed (${response.status}): ${errorText}`);
    }

    const score = response.headers.get('X-Schedule-Score');
    const status = response.headers.get('X-Schedule-Status');

    if (score) setScheduleScore(score);
    if (status) setScheduleStatus(status);

    const blob = await response.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;

    const contentDisposition = response.headers.get('Content-Disposition');
    let filename = 'output.xlsx';

    if (contentDisposition) {
      const filenameMatch = contentDisposition.match(/filename="?([^"]+)"?/);
      if (filenameMatch) {
        filename = filenameMatch[1];
      }
    }

    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setScheduleFilename(filename);
    setSuccessMessage('Schedule optimized and downloaded successfully!');
  };

  const handleOptimizeAndDownload = async () => {
    if (isRequiredDataMissing) {
      setErrorMessage(null);
      setSuccessMessage(null);
      setScheduleFilename(null);
      setScheduleScore(null);
      setScheduleStatus(null);
      return;
    }

    setIsLoading(true);
    setErrorMessage(null);
    setSuccessMessage(null);
    setScheduleFilename(null);
    setScheduleScore(null);
    setScheduleStatus(null);
    setProgressLogs(['正在啟動優化任務...']);
    setProgressValue(null);
    setIsTaskFinished(false);
    eventSourceRef.current?.close();
    eventSourceRef.current = null;

    try {
      // Prepare form data
      const formData = new FormData();
      formData.append('yaml_content', currentYaml);

      if (prettifyArg !== null && prettifyArg !== undefined) {
        formData.append('prettify', String(prettifyArg));
      }

      if (timeoutArg !== null && timeoutArg !== undefined) {
        formData.append('timeout', String(timeoutArg));
      }

      const response = await fetch(`${apiEndpoint}/optimization-jobs`, {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        // Try to parse error message from response
        const errorText = await response.text();
        let errorDetail = 'Unknown error';
        try {
          const errorJson = JSON.parse(errorText);
          errorDetail = errorJson.detail || errorText;
        } catch {
          errorDetail = errorText;
        }
        throw new Error(`Server error (${response.status}): ${errorDetail}`);
      }

      const { job_id: jobId } = await response.json();
      appendProgressLog(`任務已建立：${jobId.slice(0, 8)}`);

      const eventSource = new EventSource(`${apiEndpoint}/optimization-jobs/${jobId}/events`);
      eventSourceRef.current = eventSource;

      const handleProgressEvent = (message: Event) => {
        const data = (message as MessageEvent).data;
        if (typeof data !== 'string') {
          return;
        }
        const event = JSON.parse(data) as ProgressEvent;
        appendProgressLog(formatProgressMessage(event));
        if (event.progress !== undefined) {
          setProgressValue(event.progress);
        }
        if (event.score !== undefined) {
          setScheduleScore(String(event.score));
        }

        if (event.type === 'completed') {
          eventSource.close();
          eventSourceRef.current = null;
          setIsTaskFinished(true);
          void downloadJobResult(jobId)
            .catch((error) => {
              const message = error instanceof Error ? error.message : 'Failed to download schedule';
              appendProgressLog(`下載失敗：${message}`);
              setErrorMessage(message);
            })
            .finally(() => {
              setIsLoading(false);
            });
        }

        if (event.type === 'failed') {
          eventSource.close();
          eventSourceRef.current = null;
          setErrorMessage(event.message || 'Optimization failed');
          setIsTaskFinished(true);
          setIsLoading(false);
        }
      };

      eventSource.addEventListener('phase', handleProgressEvent);
      eventSource.addEventListener('solution', handleProgressEvent);
      eventSource.addEventListener('completed', handleProgressEvent);
      eventSource.addEventListener('failed', handleProgressEvent);
      eventSource.onerror = () => {
        eventSource.close();
        eventSourceRef.current = null;
        appendProgressLog('後端連線中斷，請確認排班伺服器是否仍在執行。');
        setErrorMessage('Connection to the optimization server was interrupted');
        setIsLoading(false);
      };
    } catch (error) {
      const message = error instanceof Error
        ? error.message
        : 'An unexpected error occurred during optimization';
      appendProgressLog(`啟動失敗：${message}`);
      setErrorMessage(message);
      setIsLoading(false);
    }
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
        <div className="flex items-center gap-3">
          <h1 className="text-3xl font-bold text-gray-800">Optimize and Export</h1>
          {instructions.length > 0 && (
            <button
              onClick={() => setShowInstructions(!showInstructions)}
              className="text-gray-500 hover:text-gray-700 transition-colors"
              title="Toggle instructions"
            >
              <FiHelpCircle className="h-6 w-6" />
            </button>
          )}
        </div>
      </div>

      {showInstructions && instructions.length > 0 && (
        <div className="mb-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
          <h3 className="text-lg font-medium text-blue-800 mb-3">Instructions</h3>
          <ul className="space-y-2 text-sm text-blue-700">
            {instructions.map((instruction, index) => (
              <li key={index}>• {instruction}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Warning Section */}
      <div className="mb-6 bg-amber-50 border border-amber-200 rounded-lg p-4">
        <h3 className="text-lg font-medium text-amber-800 mb-3 flex items-center gap-2">
          <FiAlertCircle className="h-5 w-5" />
          Warning
        </h3>
        <div className="space-y-2 text-sm text-amber-700">
          <p>
            Make sure the FastAPI server is running on the configured endpoint:  {apiEndpoint}.
            You can start the server with: <code className="bg-amber-100 px-1 py-0.5 rounded">fastapi dev core/nurse_scheduling/serve.py</code>
          </p>
        </div>
      </div>

      {/* Status Messages */}
      {errorMessage && (
        <div className="mb-6 bg-red-50 border border-red-200 rounded-lg p-4">
          <h3 className="text-lg font-medium text-red-800 mb-2 flex items-center gap-2">
            <FiAlertCircle className="h-5 w-5" />
            Error
          </h3>
          <p className="text-sm text-red-700">{errorMessage}</p>
        </div>
      )}

      {successMessage && (
        <div className="mb-6 bg-green-50 border border-green-200 rounded-lg p-4">
          <h3 className="text-lg font-medium text-green-800 mb-2 flex items-center gap-2">
            <FiCheckCircle className="h-5 w-5" />
            Success
          </h3>
          <p className="text-sm text-green-700">{successMessage}</p>
          {scheduleFilename && (
            <p className="text-sm text-green-700 mt-2">
              <strong>File:</strong> {scheduleFilename}
            </p>
          )}
          {scheduleScore && (
            <p className="text-sm text-green-700">
              <strong>Score:</strong> {scheduleScore}
            </p>
          )}
          {scheduleStatus && (
            <p className="text-sm text-green-700">
              <strong>Status:</strong> {scheduleStatus}
            </p>
          )}
        </div>
      )}

      {isRequiredDataMissing && (
        <div className="mb-6 text-center">
          <div className="text-sm text-gray-500 italic p-4 text-center border border-gray-200 rounded-lg bg-gray-50">
            {isDateDataMissing ? (
              <>
                Please set up your dates first by visiting the{' '}
                <Link href="/dates" className="text-blue-600 hover:text-blue-800 underline">
                  Dates
                </Link>{' '}
                tab.
              </>
            ) : isPeopleDataMissing ? (
              <>
                Please set up your people first by visiting the{' '}
                <Link href="/people" className="text-blue-600 hover:text-blue-800 underline">
                  People
                </Link>{' '}
                tab.
              </>
            ) : (
              <>
                Please set up your shift types first by visiting the{' '}
                <Link href="/shift-types" className="text-blue-600 hover:text-blue-800 underline">
                  Shift Types
                </Link>{' '}
                tab.
              </>
            )}
          </div>
        </div>
      )}

      {/* Configuration Form */}
      <div className="bg-white shadow-md rounded-lg overflow-hidden mb-6">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-semibold text-gray-800">Optimization Settings</h3>
        </div>

        <div className="p-6 space-y-6">
          {/* API Endpoint Input */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              API Endpoint
            </label>
            <input
              type="text"
              value={apiEndpoint}
              onChange={(e) => setApiEndpoint(e.target.value)}
              className="block w-full px-4 py-2 text-sm text-gray-900 bg-white border border-gray-300 rounded-lg shadow-sm transition-colors duration-200 ease-in-out focus:border-blue-500 focus:ring-blue-200 placeholder-gray-400 focus:outline-none focus:ring-2 hover:border-gray-400"
              placeholder="http://localhost:8000"
            />
            <p className="mt-1 text-sm text-gray-500">
              URL of the backend scheduling server
            </p>
          </div>

          {/* Prettify Option */}
          <div className="flex items-center gap-4">
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={prettifyArg}
                onChange={(e) => setPrettifyArg(e.target.checked)}
                className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
              />
              <span className="text-sm font-medium text-gray-700">
                Enable Prettify
              </span>
            </label>
            <span className="text-sm text-gray-500">
              (Prettier output formatting in generated schedule)
            </span>
          </div>

          {/* Timeout Input */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Solver Timeout (seconds)
            </label>
            <input
              type="number"
              value={timeoutArg}
              onChange={(e) => setTimeoutArg(parseInt(e.target.value) || 300)}
              min="1"
              max="3600"
              className="block w-full px-4 py-2 text-sm text-gray-900 bg-white border border-gray-300 rounded-lg shadow-sm transition-colors duration-200 ease-in-out focus:border-blue-500 focus:ring-blue-200 placeholder-gray-400 focus:outline-none focus:ring-2 hover:border-gray-400"
              placeholder="300"
            />
            <p className="mt-1 text-sm text-gray-500">
              Maximum time the optimizer will run (1-3600 seconds)
            </p>
          </div>

          {/* Action Button */}
          <div className="flex justify-end">
            <button
              onClick={handleOptimizeAndDownload}
              disabled={isLoading || isRequiredDataMissing}
              className={`flex items-center gap-2 px-6 py-2 font-medium rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 ${
                isLoading || isRequiredDataMissing
                  ? 'bg-gray-400 cursor-not-allowed text-white'
                  : 'bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500'
              }`}
            >
              {isLoading ? (
                <>
                  <FiLoader className="h-5 w-5 animate-spin" />
                  Optimizing...
                </>
              ) : (
                <>
                  <FiDownload className="h-5 w-5" />
                  Optimize and Download
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {(isLoading || isTaskFinished || progressLogs.length > 0) && (
        <div className="mb-6 bg-gray-900 text-green-300 rounded-lg shadow-md overflow-hidden">
          <div className="px-6 py-4 bg-gray-800 flex items-center justify-between gap-4">
            <h3 className="text-lg font-semibold">即時優化日誌</h3>
            {isLoading ? (
              <FiLoader className="animate-spin h-5 w-5 flex-shrink-0" />
            ) : isTaskFinished ? (
              <span className="text-sm font-semibold text-green-300">已完成</span>
            ) : null}
          </div>
          {progressValue !== null && (
            <div className="px-6 pt-4">
              <div className="h-2 bg-gray-700 rounded overflow-hidden">
                <div
                  className="h-2 bg-green-400 transition-all"
                  style={{ width: `${Math.round(progressValue * 100)}%` }}
                />
              </div>
            </div>
          )}
          <pre className="p-6 h-72 overflow-auto font-mono text-sm leading-relaxed whitespace-pre-wrap">
            {progressLogs.join('\n')}
          </pre>
        </div>
      )}

      {/* YAML Preview */}
      <div className="bg-white shadow-md rounded-lg overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-semibold text-gray-800">YAML Preview</h3>
          <p className="text-sm text-gray-600 mt-1">
            This is the configuration that will be sent to the optimization server
          </p>
        </div>

        <div className="relative">
          <pre
            className="w-full h-96 p-4 font-mono text-sm overflow-auto bg-gray-50 whitespace-pre-wrap"
            style={{ fontFamily: 'ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace' }}
          >
            {currentYaml}
          </pre>
        </div>
      </div>
    </div>
  );
}
