/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { act } from 'react';
import OptimizeAndExportPage from '@/app/optimize-and-export/page';

const mockUseSchedulingData = vi.hoisted(() => vi.fn());
const mockGenerateYamlFromState = vi.hoisted(() => vi.fn());

vi.mock('@/hooks/useSchedulingData', () => ({
  useSchedulingData: mockUseSchedulingData,
}));

vi.mock('@/utils/yamlGenerator', () => ({
  generateYamlFromState: mockGenerateYamlFromState,
}));

class MockEventSource {
  static instances: MockEventSource[] = [];

  listeners = new Map<string, Array<(event: MessageEvent) => void>>();
  url: string;
  close = vi.fn();

  constructor(url: string) {
    this.url = url;
    MockEventSource.instances.push(this);
  }

  addEventListener(type: string, listener: (event: MessageEvent) => void) {
    this.listeners.set(type, [...(this.listeners.get(type) ?? []), listener]);
  }

  emit(type: string, data: unknown) {
    const event = new MessageEvent(type, {
      data: typeof data === 'string' ? data : JSON.stringify(data),
    });
    this.listeners.get(type)?.forEach(listener => listener(event));
  }
}

describe('OptimizeAndExportPage error handling', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    MockEventSource.instances = [];
    mockGenerateYamlFromState.mockReturnValue('apiVersion: alpha\ndescription: baseline\n');
    mockUseSchedulingData.mockReturnValue({
      apiVersionData: 'alpha',
      descriptionData: 'baseline',
      dateData: { range: { startDate: undefined, endDate: undefined }, items: [], groups: [] },
      peopleData: { items: [{ id: 'P1', description: '', history: [] }], groups: [], history: [] },
      shiftTypeData: { items: [{ id: 'D', description: '' }], groups: [] },
      preferences: [],
      exportData: { formatting: [] },
      filterAutoGeneratedState: vi.fn(state => state),
    });
    vi.stubGlobal('fetch', vi.fn());
    vi.stubGlobal('EventSource', undefined);
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:mock');
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
  });

  it('surfaces raw non-JSON error bodies from the backend', async () => {
    const user = userEvent.setup();
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: false,
      status: 503,
      text: vi.fn().mockResolvedValue('service unavailable'),
    });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (503): service unavailable')).resolves.toBeInTheDocument();
  });

  it('falls back to the raw JSON text when the backend error body has no detail field', async () => {
    const user = userEvent.setup();
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: false,
      status: 422,
      text: vi.fn().mockResolvedValue(JSON.stringify({ error: 'validation failed' })),
    });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (422): {"error":"validation failed"}')).resolves.toBeInTheDocument();
  });

  it('keeps showing the raw response text when JSON parsing itself fails', async () => {
    const user = userEvent.setup();
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: false,
      status: 500,
      text: vi.fn().mockResolvedValue('{bad json'),
    });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (500): {bad json')).resolves.toBeInTheDocument();
  });

  it('shows backend health status from the health endpoint', async () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: true,
      json: vi.fn().mockResolvedValue({
        status: 'ok',
        version: 'alpha',
        apiVersion: 'alpha',
        appVersion: 'v-test',
      }),
    });

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText('Server: Online')).resolves.toBeInTheDocument();
    expect(screen.getByText(/API version: alpha · App version: v-test/)).toBeInTheDocument();
  });

  it('creates an optimization job, downloads the XLSX, and deletes the job', async () => {
    const user = userEvent.setup();
    const appendChildSpy = vi.spyOn(document.body, 'appendChild');
    const removeChildSpy = vi.spyOn(document.body, 'removeChild');

    (fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          status: 'ok',
          version: 'alpha',
          apiVersion: 'alpha',
          appVersion: 'v-test',
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_test',
          status: 'queued',
          score: null,
          solverStatus: null,
          error: null,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_test',
            events: '/optimize/opt_test/events',
            xlsx: '/optimize/opt_test/xlsx',
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_test',
          status: 'optimal',
          score: 42,
          solverStatus: 'OPTIMAL',
          error: null,
          xlsxReady: true,
          links: {
            status: '/optimize/opt_test',
            events: '/optimize/opt_test/events',
            xlsx: '/optimize/opt_test/xlsx',
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(new Blob(['xlsx'])),
        headers: new Headers({
          'Content-Disposition': 'attachment; filename=schedule.xlsx',
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
      });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Schedule optimized and downloaded successfully!')).resolves.toBeInTheDocument();
    expect(screen.getByText('schedule.xlsx')).toBeInTheDocument();
    expect(screen.getByText('42')).toBeInTheDocument();
    expect(screen.getByText('OPTIMAL')).toBeInTheDocument();

    expect(fetch).toHaveBeenCalledWith('http://localhost:8000/optimize', expect.objectContaining({ method: 'POST' }));
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_test',
      expect.objectContaining({ method: 'GET' })
    );
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_test/xlsx',
      expect.objectContaining({ method: 'GET' })
    );
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_test',
      expect.objectContaining({ method: 'DELETE' })
    );
    expect(appendChildSpy).toHaveBeenCalled();
    expect(removeChildSpy).toHaveBeenCalled();
  });

  it('shows all received SSE event types in the optimization event log', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);

    (fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          status: 'ok',
          version: 'alpha',
          apiVersion: 'alpha',
          appVersion: 'v-test',
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_sse',
          status: 'queued',
          score: null,
          solverStatus: null,
          error: null,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_sse',
            events: '/optimize/opt_sse/events',
            xlsx: '/optimize/opt_sse/xlsx',
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(new Blob(['xlsx'])),
        headers: new Headers({
          'Content-Disposition': 'attachment; filename=schedule.xlsx',
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
      });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    const eventSource = MockEventSource.instances[0];
    expect(eventSource.url).toBe('http://localhost:8000/optimize/opt_sse/events');
    act(() => {
      eventSource.emit('status', { status: 'running' });
      eventSource.emit('progress', { bestScore: 12, solutionCount: 1 });
      eventSource.emit('complete', {
        jobId: 'opt_sse',
        status: 'optimal',
        score: 42,
        solverStatus: 'OPTIMAL',
        error: null,
        xlsxReady: true,
        links: {
          status: '/optimize/opt_sse',
          events: '/optimize/opt_sse/events',
          xlsx: '/optimize/opt_sse/xlsx',
        },
      });
    });

    await expect(screen.findByText('Schedule optimized and downloaded successfully!')).resolves.toBeInTheDocument();
    expect(screen.getByText('status')).toBeInTheDocument();
    expect(screen.getByText('progress')).toBeInTheDocument();
    expect(screen.getByText('complete')).toBeInTheDocument();
    expect(screen.getByText(/"bestScore":12/)).toBeInTheDocument();
    expect(eventSource.close).toHaveBeenCalled();
  });
});
