// The Optimize and Export page for "Tab. 10. Optimize and Export"
'use client';

import { useState } from 'react';
import { FiHelpCircle, FiDownload, FiAlertCircle, FiCheckCircle, FiLoader } from 'react-icons/fi';
import { useSchedulingData } from '@/hooks/useSchedulingData';
import { generateYamlFromState } from '@/utils/yamlGenerator';

export default function OptimizeAndExportPage() {
  const {
    apiVersionData,
    descriptionData,
    dateData,
    peopleData,
    shiftTypeData,
    preferences,
    filterAutoGeneratedState
  } = useSchedulingData();

  const [showInstructions, setShowInstructions] = useState(false);
  const [apiEndpoint, setApiEndpoint] = useState(process.env.BACKEND_API_URL || 'http://localhost:8000');
  const [prettifyArg, setPrettifyArg] = useState(true);
  const [timeoutArg, setTimeoutArg] = useState<number>(300);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [scheduleFilename, setScheduleFilename] = useState<string | null>(null);
  const [scheduleScore, setScheduleScore] = useState<string | null>(null);
  const [scheduleStatus, setScheduleStatus] = useState<string | null>(null);

  const instructions = [
    "This page sends your current scheduling configuration to the optimization server",
    "The server will compute an optimal schedule and return an Excel (.xlsx) file",
    "Configure optimization options (prettify and timeout) before submitting",
    "Prettify: Enables prettier output formatting in the generated schedule",
    "Timeout: Maximum time (in seconds) the optimizer will run before stopping",
    "Click 'Optimize and Download' to generate your schedule",
    "The optimization score and status will be displayed after completion"
  ];

  // Create the current state object for YAML export (filtering out autogenerated items)
  const filteredState = filterAutoGeneratedState({
    apiVersion: apiVersionData,
    description: descriptionData,
    dates: dateData,
    people: peopleData,
    shiftTypes: shiftTypeData,
    preferences
  });

  // Convert current state to YAML
  const currentYaml = generateYamlFromState(filteredState);

  const handleOptimizeAndDownload = async () => {
    setIsLoading(true);
    setErrorMessage(null);
    setSuccessMessage(null);
    setScheduleFilename(null);
    setScheduleScore(null);
    setScheduleStatus(null);

    try {
      // Prepare form data
      const formData = new FormData();
      formData.append('yaml_content', currentYaml);

      if (prettifyArg !== null && prettifyArg !== undefined) {
        formData.append('prettify', String(prettifyArg));
      }

      if (timeoutArg !== null && timeoutArg !== undefined) {
        formData.append('timeout', String(timeoutArg));
      }

      // Send request to FastAPI server
      const response = await fetch(`${apiEndpoint}/optimize-and-export-xlsx`, {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        // Try to parse error message from response
        const errorText = await response.text();
        let errorDetail = 'Unknown error';
        try {
          const errorJson = JSON.parse(errorText);
          errorDetail = errorJson.detail || errorText;
        } catch {
          errorDetail = errorText;
        }
        throw new Error(`Server error (${response.status}): ${errorDetail}`);
      }

      // Extract custom headers with score and status
      const score = response.headers.get('X-Schedule-Score');
      const status = response.headers.get('X-Schedule-Status');

      if (score) setScheduleScore(score);
      if (status) setScheduleStatus(status);

      // Get the blob data (XLSX file)
      const blob = await response.blob();

      // Create download link
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;

      // Extract filename from Content-Disposition header or use default
      const contentDisposition = response.headers.get('Content-Disposition');
      let filename = `output.xlsx`;

      if (contentDisposition) {
        const filenameMatch = contentDisposition.match(/filename="?([^"]+)"?/);
        if (filenameMatch) {
          filename = filenameMatch[1];
        }
      }

      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      setScheduleFilename(filename);
      setSuccessMessage('Schedule optimized and downloaded successfully!');
    } catch (error) {
      console.error('Error during optimization:', error);
      setErrorMessage(
        error instanceof Error
          ? error.message
          : 'An unexpected error occurred during optimization'
      );
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
        <div className="flex items-center gap-3">
          <h1 className="text-3xl font-bold text-gray-800">Optimize and Export</h1>
          {instructions.length > 0 && (
            <button
              onClick={() => setShowInstructions(!showInstructions)}
              className="text-gray-500 hover:text-gray-700 transition-colors"
              title="Toggle instructions"
            >
              <FiHelpCircle className="h-6 w-6" />
            </button>
          )}
        </div>
      </div>

      {showInstructions && instructions.length > 0 && (
        <div className="mb-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
          <h3 className="text-lg font-medium text-blue-800 mb-3">Instructions</h3>
          <ul className="space-y-2 text-sm text-blue-700">
            {instructions.map((instruction, index) => (
              <li key={index}>• {instruction}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Warning Section */}
      <div className="mb-6 bg-amber-50 border border-amber-200 rounded-lg p-4">
        <h3 className="text-lg font-medium text-amber-800 mb-3 flex items-center gap-2">
          <FiAlertCircle className="h-5 w-5" />
          Warning
        </h3>
        <div className="space-y-2 text-sm text-amber-700">
          <p>
            Make sure the FastAPI server is running on the configured endpoint:  {apiEndpoint}.
            You can start the server with: <code className="bg-amber-100 px-1 py-0.5 rounded">fastapi dev core/nurse_scheduling/serve.py</code>
          </p>
        </div>
      </div>

      {/* Status Messages */}
      {errorMessage && (
        <div className="mb-6 bg-red-50 border border-red-200 rounded-lg p-4">
          <h3 className="text-lg font-medium text-red-800 mb-2 flex items-center gap-2">
            <FiAlertCircle className="h-5 w-5" />
            Error
          </h3>
          <p className="text-sm text-red-700">{errorMessage}</p>
        </div>
      )}

      {successMessage && (
        <div className="mb-6 bg-green-50 border border-green-200 rounded-lg p-4">
          <h3 className="text-lg font-medium text-green-800 mb-2 flex items-center gap-2">
            <FiCheckCircle className="h-5 w-5" />
            Success
          </h3>
          <p className="text-sm text-green-700">{successMessage}</p>
          {scheduleFilename && (
            <p className="text-sm text-green-700 mt-2">
              <strong>File:</strong> {scheduleFilename}
            </p>
          )}
          {scheduleScore && (
            <p className="text-sm text-green-700">
              <strong>Score:</strong> {scheduleScore}
            </p>
          )}
          {scheduleStatus && (
            <p className="text-sm text-green-700">
              <strong>Status:</strong> {scheduleStatus}
            </p>
          )}
        </div>
      )}

      {/* Configuration Form */}
      <div className="bg-white shadow-md rounded-lg overflow-hidden mb-6">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-semibold text-gray-800">Optimization Settings</h3>
        </div>

        <div className="p-6 space-y-6">
          {/* API Endpoint Input */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              API Endpoint
            </label>
            <input
              type="text"
              value={apiEndpoint}
              onChange={(e) => setApiEndpoint(e.target.value)}
              className="block w-full px-4 py-2 text-sm text-gray-900 bg-white border border-gray-300 rounded-lg shadow-sm transition-colors duration-200 ease-in-out focus:border-blue-500 focus:ring-blue-200 placeholder-gray-400 focus:outline-none focus:ring-2 hover:border-gray-400"
              placeholder="http://localhost:8000"
            />
            <p className="mt-1 text-sm text-gray-500">
              URL of the backend scheduling server
            </p>
          </div>

          {/* Prettify Option */}
          <div className="flex items-center gap-4">
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={prettifyArg}
                onChange={(e) => setPrettifyArg(e.target.checked)}
                className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
              />
              <span className="text-sm font-medium text-gray-700">
                Enable Prettify
              </span>
            </label>
            <span className="text-sm text-gray-500">
              (Prettier output formatting in generated schedule)
            </span>
          </div>

          {/* Timeout Input */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Timeout (seconds)
            </label>
            <input
              type="number"
              value={timeoutArg}
              onChange={(e) => setTimeoutArg(parseInt(e.target.value) || 300)}
              min="1"
              max="3600"
              className="block w-full px-4 py-2 text-sm text-gray-900 bg-white border border-gray-300 rounded-lg shadow-sm transition-colors duration-200 ease-in-out focus:border-blue-500 focus:ring-blue-200 placeholder-gray-400 focus:outline-none focus:ring-2 hover:border-gray-400"
              placeholder="300"
            />
            <p className="mt-1 text-sm text-gray-500">
              Maximum time the optimizer will run (1-3600 seconds)
            </p>
          </div>

          {/* Action Button */}
          <div className="flex justify-end">
            <button
              onClick={handleOptimizeAndDownload}
              disabled={isLoading}
              className={`flex items-center gap-2 px-6 py-2 font-medium rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 ${
                isLoading
                  ? 'bg-gray-400 cursor-not-allowed text-white'
                  : 'bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500'
              }`}
            >
              {isLoading ? (
                <>
                  <FiLoader className="h-5 w-5 animate-spin" />
                  Optimizing...
                </>
              ) : (
                <>
                  <FiDownload className="h-5 w-5" />
                  Optimize and Download
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* YAML Preview */}
      <div className="bg-white shadow-md rounded-lg overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-semibold text-gray-800">YAML Preview</h3>
          <p className="text-sm text-gray-600 mt-1">
            This is the configuration that will be sent to the optimization server
          </p>
        </div>

        <div className="relative">
          <pre
            className="w-full h-96 p-4 font-mono text-sm overflow-auto bg-gray-50 whitespace-pre-wrap"
            style={{ fontFamily: 'ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace' }}
          >
            {currentYaml}
          </pre>
        </div>
      </div>
    </div>
  );
}
