/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import OptimizeAndExportPage from '@/app/optimize-and-export/page';

const mockUseSchedulingData = vi.hoisted(() => vi.fn());
const mockGenerateYamlFromState = vi.hoisted(() => vi.fn());

vi.mock('@/hooks/useSchedulingData', () => ({
  useSchedulingData: mockUseSchedulingData,
}));

vi.mock('@/utils/yamlGenerator', () => ({
  generateYamlFromState: mockGenerateYamlFromState,
}));

describe('OptimizeAndExportPage error handling', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    mockGenerateYamlFromState.mockReturnValue('apiVersion: alpha\ndescription: baseline\n');
    mockUseSchedulingData.mockReturnValue({
      apiVersionData: 'alpha',
      descriptionData: 'baseline',
      dateData: { range: { startDate: undefined, endDate: undefined }, items: [], groups: [] },
      peopleData: { items: [{ id: 'P1', description: '', history: [] }], groups: [], history: [] },
      shiftTypeData: { items: [{ id: 'D', description: '' }], groups: [] },
      preferences: [],
      exportData: { formatting: [] },
      filterAutoGeneratedState: vi.fn(state => state),
    });
    vi.stubGlobal('fetch', vi.fn());
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:mock');
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
  });

  it('surfaces raw non-JSON error bodies from the backend', async () => {
    const user = userEvent.setup();
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: false,
      status: 503,
      text: vi.fn().mockResolvedValue('service unavailable'),
    });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (503): service unavailable')).resolves.toBeInTheDocument();
  });

  it('falls back to the raw JSON text when the backend error body has no detail field', async () => {
    const user = userEvent.setup();
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: false,
      status: 422,
      text: vi.fn().mockResolvedValue(JSON.stringify({ error: 'validation failed' })),
    });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (422): {"error":"validation failed"}')).resolves.toBeInTheDocument();
  });

  it('keeps showing the raw response text when JSON parsing itself fails', async () => {
    const user = userEvent.setup();
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: false,
      status: 500,
      text: vi.fn().mockResolvedValue('{bad json'),
    });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (500): {bad json')).resolves.toBeInTheDocument();
  });

  it('shows backend health status from the health endpoint', async () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: true,
      json: vi.fn().mockResolvedValue({
        status: 'ok',
        version: 'alpha',
        apiVersion: 'alpha',
        appVersion: 'v-test',
      }),
    });

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText('Server: Online')).resolves.toBeInTheDocument();
    expect(screen.getByText(/API version: alpha · App version: v-test/)).toBeInTheDocument();
  });
});
