/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { act, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import OptimizeAndExportPage from '@/app/optimize-and-export/page';

const mockUseSchedulingData = vi.hoisted(() => vi.fn());
const mockGenerateYamlFromState = vi.hoisted(() => vi.fn());

vi.mock('@/hooks/useSchedulingData', () => ({
  useSchedulingData: mockUseSchedulingData,
}));

vi.mock('@/utils/yamlGenerator', () => ({
  generateYamlFromState: mockGenerateYamlFromState,
}));

class MockEventSource {
  static instances: MockEventSource[] = [];
  listeners = new Map<string, Array<(event: MessageEvent) => void>>();
  onerror: (() => void) | null = null;
  url: string;

  constructor(url: string) {
    this.url = url;
    MockEventSource.instances.push(this);
  }

  addEventListener(type: string, listener: (event: MessageEvent) => void) {
    this.listeners.set(type, [...(this.listeners.get(type) ?? []), listener]);
  }

  close() {
    return undefined;
  }

  emit(type: string, data: string) {
    for (const listener of this.listeners.get(type) ?? []) {
      listener({ data } as MessageEvent);
    }
  }
}

const createSchedulingData = (overrides = {}) => ({
  apiVersionData: 'alpha',
  descriptionData: 'baseline',
  dateData: {
    range: { startDate: new Date('2026-09-01'), endDate: new Date('2026-09-01') },
    items: [{ id: '01', description: '' }],
    groups: [],
  },
  peopleData: { items: [{ id: 'P1', description: '', history: [] }], groups: [], history: [] },
  shiftTypeData: { items: [{ id: 'D', description: '' }], groups: [] },
  preferences: [],
  exportData: { formatting: [] },
  filterAutoGeneratedState: vi.fn(state => state),
  ...overrides,
});

describe('OptimizeAndExportPage error handling', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    mockGenerateYamlFromState.mockReturnValue('apiVersion: alpha\ndescription: baseline\n');
    mockUseSchedulingData.mockReturnValue(createSchedulingData());
    vi.stubGlobal('fetch', vi.fn());
    vi.stubGlobal('EventSource', MockEventSource);
    MockEventSource.instances = [];
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:mock');
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
  });

  it('surfaces raw non-JSON error bodies from the backend', async () => {
    const user = userEvent.setup();
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: false,
      status: 503,
      text: vi.fn().mockResolvedValue('service unavailable'),
    });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (503): service unavailable')).resolves.toBeInTheDocument();
  });

  it('falls back to the raw JSON text when the backend error body has no detail field', async () => {
    const user = userEvent.setup();
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: false,
      status: 422,
      text: vi.fn().mockResolvedValue(JSON.stringify({ error: 'validation failed' })),
    });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (422): {"error":"validation failed"}')).resolves.toBeInTheDocument();
  });

  it('keeps showing the raw response text when JSON parsing itself fails', async () => {
    const user = userEvent.setup();
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: false,
      status: 500,
      text: vi.fn().mockResolvedValue('{bad json'),
    });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (500): {bad json')).resolves.toBeInTheDocument();
  });

  it('ignores malformed progress events without leaving the task stuck', async () => {
    const user = userEvent.setup();
    (fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({ job_id: 'job-1' }),
      })
      .mockResolvedValueOnce({
        ok: true,
        headers: new Headers({
          'Content-Disposition': 'attachment; filename="schedule.xlsx"',
          'X-Schedule-Score': '0',
          'X-Schedule-Status': 'OPTIMAL',
        }),
        blob: vi.fn().mockResolvedValue(new Blob(['xlsx'])),
      });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    act(() => {
      MockEventSource.instances[0].emit('phase', '{bad json');
    });
    await expect(screen.findByText(/Received an invalid progress event\./)).resolves.toBeInTheDocument();

    act(() => {
      MockEventSource.instances[0].emit(
        'completed',
        '{"type":"completed","code":"completed","message":"Optimization completed","progress":1,"score":0}'
      );
    });
    await expect(screen.findByText('Schedule optimized and downloaded successfully!')).resolves.toBeInTheDocument();
  });

  it('forbids sending and instructs users to set dates when date data is empty', async () => {
    const user = userEvent.setup();
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      dateData: { range: { startDate: undefined, endDate: undefined }, items: [], groups: [] },
    }));

    render(<OptimizeAndExportPage />);

    expect(screen.getByText(/Please set up your dates first by visiting the/i)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Dates' })).toHaveAttribute('href', '/dates');

    const optimizeButton = screen.getByRole('button', { name: /optimize and download/i });
    expect(optimizeButton).toBeDisabled();
    await user.click(optimizeButton);

    expect(fetch).not.toHaveBeenCalled();
  });

  it('forbids sending and instructs users to set people when people data is empty', async () => {
    const user = userEvent.setup();
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      peopleData: { items: [], groups: [], history: [] },
    }));

    render(<OptimizeAndExportPage />);

    expect(screen.getByText(/Please set up your people first by visiting the/i)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'People' })).toHaveAttribute('href', '/people');

    const optimizeButton = screen.getByRole('button', { name: /optimize and download/i });
    expect(optimizeButton).toBeDisabled();
    await user.click(optimizeButton);

    expect(fetch).not.toHaveBeenCalled();
  });

  it('forbids sending and instructs users to set shift types when shift type data is empty', async () => {
    const user = userEvent.setup();
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      shiftTypeData: { items: [], groups: [] },
    }));

    render(<OptimizeAndExportPage />);

    expect(screen.getByText(/Please set up your shift types first by visiting the/i)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Shift Types' })).toHaveAttribute('href', '/shift-types');

    const optimizeButton = screen.getByRole('button', { name: /optimize and download/i });
    expect(optimizeButton).toBeDisabled();
    await user.click(optimizeButton);

    expect(fetch).not.toHaveBeenCalled();
  });
});
